1주차 과제1 -  let을 사용하지 않고 개발하기
CodeSoom/week1-assignment-1 pull request #190
Opened 2022-08-02 11:30 UTC by ChoJinmok

## :: 최근 작업 주제
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표
- let을 사용하지 않고 개발하기
<br />

## :: 구현 사항 설명
1. 객체로 구현
- counter, handler를 객체로 묶어 줬습니다.

<br />

## :: 기타 질문 및 특이 사항
- 객체 프로퍼티를 갱신하는 것도 재할당에 들어간다면 죄송합니다..

2022-08-02 12:24 UTC, daadaadaah requested changes
객체는 `const` 일 때도 속성이 변경이 가능하다는 점을 이용해서 문제를 해결하려고 하셨군요!
좋은 시도였지만, `let` 을 없애려는 의도에 대해 한번 고민해보시면 좋을 것 같아요!
`let`을 없애고 외부 변수 없이 값을 직접 변경할 수 있는 방법은 없을까요? 🤔

2022-08-03 09:49 UTC, ChoJinmok reviewed
1. 1차 제출시에 저는 let을 제한하신 이유가 변수가 오염될 수 있는 위험이 있어서라고 생각했습니다! 그래서 객체로 묶어줌으로서 오염 위험도를 낮춰보려고 했었습니다!
2. 외부 변수 없이 함수 안에서 값을 변경할 수 있는 방법은 매개변수를 만들어서 인자로 전달받아 값을 변경할 수 있지 않을까 해서 위의 구현 사항과 같이 구현해봤습니다.

2022-08-03 13:51 UTC, daadaadaah requested changes
과제 다 수행하시고 코드 리팩토링으로 한번 체크 해보신 점 너무 좋네용!👍
다만, 지금은 render 함수밖에 없지만, handleClick 함수로 빼서 사용하는게 나중에 유지보수 측면에서 더 좋다고 생각합니다!ㅎㅎ

2022-08-03 13:51 UTC, daadaadaah commented on src/index.js
> +function handleClick(value) {
`value` 라는 추상적인 표현보다 좀더 의도가 드러나는 단어는 없을까요? 🤔

2022-08-03 13:51 UTC, daadaadaah commented on src/index.js
> +  const count = value || 0;
이 코드 대신에 다른 방법으로 value가 없을 때, count에 0을 넣어주는 방법은 없을까요? 🤔

2022-08-04 06:12 UTC, ChoJinmok commented on src/index.js
> +function handleClick(value) {
단순하게 강의에 나온 코드를 따라 쳤는데 반성하게 되네요 😭
매개변수를 number로 바꿔봐야겠네요!

2022-08-04 06:14 UTC, ChoJinmok commented on src/index.js
> +  const count = value || 0;
ES6 문법을 알고있었는데... 앞으로는 매개변수에 기본값 설정을 하는 습관을 들여야겠네요!!
리뷰 감사합니다!

2022-08-04 06:24 UTC, ChoJinmok reviewed
리뷰 반영 완료했습니다!~🙂

2022-08-04 12:14 UTC, daadaadaah requested changes
`4. 숫자 버튼들을 map해줄 때 map의 콜백함수 매개변수명 구체적 단어로 변경` 이 작업 스스로 수정할 곳을 찾아 수정하신 점 너무 잘하셨어요!👏 항상 코드 제출 전에 한번도 검토해보는 습관 너무 좋죠!👍

1. commit 안에 어떤 작업을 했는지 기재해주셔서 좋았습니다. 좀더 작업 내역을 잘 관리하고 싶으시면, 1개의 commit에 모든 작업이 들어가는게 아니라, 작업별로 commit 남겨보세요~ㅎㅎ

2022-08-04 12:14 UTC, daadaadaah commented on src/index.js
> +  const count = number;
27~28줄을 아래처럼 작성해주면 간단해질 것 같은데, 따로 해주신 특별한 이유가 있으신가요?ㅎㅎ 
```js
function render(count = 0) {

```

2022-08-04 12:14 UTC, daadaadaah commented on src/index.js
> +        {[1, 2, 3].map((btnNumber) => (
27~28줄을 number를 없애고 counter를 사용하게 되면, `btnNumber` 대신 `number`를 사용할 수 있을 것 같은데, 어떻게 생각하시나요? ㅎㅎ

2022-08-04 12:21 UTC, ChoJinmok commented on src/index.js
> +  const count = number;
매개변수 같은 경우에는 함수안에서 변경이 가능하기 때문에 변수가 오염이 될 수도 있다고 생각했습니다!  🥲

2022-08-04 12:25 UTC, ChoJinmok commented on src/index.js
> +        {[1, 2, 3].map((btnNumber) => (
안그래도 이 부분 수정할 때 찝찝했는데...
counter로 사용하면 훨씬 코드가 간결해지는 것 같습니다!!!👍

2022-08-04 14:28 UTC, daadaadaah commented on src/index.js
> +        {[1, 2, 3].map((btnNumber) => (
스스로 이상한 점을 느낀 거 좋은 시그널이라고 생각합니다👍

2022-08-05 06:18 UTC, ChoJinmok reviewed
작업별로 commit 하는 습관이 안돼있다보니 또 합쳐서 commit 해버렸습니다.. 리뷰까지 해주셨는데 죄송합니다!! 리뷰해주신대로 작업별로 commit 하는 습관 들여보겠습니다!

2022-08-05 12:03 UTC, daadaadaah commented on src/index.js
> +/* eslint no-use-before-define: ["error", { "functions": false }] */
왜 `no-use-before-define` 룰이 사용되는지에 대해 한 번더 생각해보시면 좋을 것 같아요!
참고 : https://eslint.org/docs/rules/no-use-before-define
 lint 문제를 근본적으로 해결하려면 어떻게 해야 할까요? 🤔

2022-08-05 12:13 UTC, ChoJinmok commented on src/index.js
> +/* eslint no-use-before-define: ["error", { "functions": false }] */
함수 안으로 중첩하면 해결되는 것 같습니다..!😭

2022-08-05 12:20 UTC, daadaadaah approved these changes

2022-08-08 06:20 UTC, merged