remove let
CodeSoom/week1-assignment-1 pull request #191
Opened 2022-08-02 15:19 UTC by violet4795

- render 내 변수로 통합

2022-08-03 11:38 UTC, daadaadaah reviewed
빠르게 PR 잘 날려주셨습니당! 👍
다만, 앞으로 코드숨 과제하면서 PR 보내시기 전에 lint 한번만 체크해주세요~ㅎㅎ

2022-08-03 11:38 UTC, daadaadaah commented on src/index.js
> +  console.log(children);
PR 보내시기 전에 콘솔은 정리해주시면 좋아요!

2022-08-03 14:45 UTC, violet4795 commented on src/index.js
> +  console.log(children);
앝..! 수정했습니다. 린팅도 해서 다시올리겠습니당!

2022-08-04 12:34 UTC, daadaadaah requested changes

2022-08-04 12:34 UTC, daadaadaah commented on src/index.js
> +  render(number);
왜 `no-use-before-define` 룰이 사용되는데 한 번더 생각해보시면 좋을 것 같아요!
참고 : https://eslint.org/docs/rules/no-use-before-define
 lint 문제를 근본적으로 해결하려면 어떻게 해야 할까요? 🤔

2022-08-04 13:02 UTC, violet4795 commented on src/index.js
> +  render(number);
이코드에서는 안에서 쓰는거니까 안에 넣어서 해결하면 될것같네요!

2022-08-05 12:06 UTC, daadaadaah requested changes
코드를 다 작성하시고 리팩터링을 생각해보시는 건 너무 좋은 프로세스였던 것 같아요!👍 
다만, https://github.com/CodeSoom/react-week1-assignment-1/pull/191/commits/b48a3eb8fd612a82dbdaa53d55fd6fd03c79be51 을 보시면, 수정 전 코드가 나중에 유지보수하기에 더 괜찮을 것 같아요!

2022-08-06 11:42 UTC, daadaadaah requested changes

2022-08-06 11:42 UTC, daadaadaah commented on src/index.js
> +          <button type="button" onClick={() => render(i)}>
여기도 같이 바꿔주시면 좋을 것 같아요!ㅎㅎ

2022-08-06 14:01 UTC, violet4795 commented on src/index.js
> +          <button type="button" onClick={() => render(i)}>
앗,...!!!

2022-08-08 06:20 UTC, merged