1주차 과제 1, let을 제거해보자
CodeSoom/week1-assignment-1 pull request #192
Opened 2022-08-03 11:49 UTC by xunxee

- 재할당을 하지 않으면서 기존과 동일한 결과를 만들기 위해서
  함수의 매개변수를 사용하여 문제를 해결해나가고자 생각했습니다.
- 개발 환경을 구축하고 강의 내용을 이해하는데 많은 시간이 필요했습니다.
  문제를 해결하지 못했지만 commit을 남겨봅니다.

2022-08-03 12:04 UTC, daadaadaah reviewed
과제가 다 완성되지 않았지만, 용기있게 PR 날려주신 점 너무 좋습니다!👍
계속 진행해주세요🚀

2022-08-03 12:04 UTC, daadaadaah commented on src/index.js
> +      {[1, 2, 3].map((num) => (
축약어보다 number 이렇게 모두 기재해주는 습관을 가져봅시다!ㅎㅎ

2022-08-03 12:04 UTC, daadaadaah commented on src/index.js
> +  function handleClickNumber(value) {
코드 수정하실 때, `value` 같은 추상적인 네이밍보다 좀더 의도가 드러나는 네이밍이 없을까? 한번 고민해보세요~ㅎㅎ

2022-08-04 12:47 UTC, daadaadaah requested changes
commit 안에 어떤 작업을 했는지 기재해주신 점 너무 좋습니다! 👍
좀더 작업 내역을 잘 관리하고 싶으시면, 1개의 commit에 모든 작업이 들어가는게 아니라, 작업별로 commit 남겨보세요~ㅎㅎ

2022-08-04 12:47 UTC, daadaadaah commented on src/index.js
> +function render(count = 1) {
기본값을 0 -> 1 로 바꿔 주신 특별한 이유가 있으신가용?ㅎㅎ

2022-08-04 12:47 UTC, daadaadaah commented on src/index.js
> +      {[1, 2, 3].map((buttonNumber) => (
FullName으로 기재해주신 점 너무 좋습니다!
그런데, `number`로 해도 의미상 문제가 없을 것 같은데, 어떻게 생각하시나요?ㅎㅎ

2022-08-05 04:37 UTC, xunxee commented on src/index.js
> +function render(count = 1) {
앗, 제가 실수로 0에서 1로 바꾸었네요!
다시 0으로 수정했습니당 ㅎㅎ

2022-08-05 04:40 UTC, xunxee commented on src/index.js
> +      {[1, 2, 3].map((buttonNumber) => (
number로 해도 충분히 의미가 전달되는 것 같습니당!
감사합니다 🐥

2022-08-05 12:08 UTC, daadaadaah commented on src/index.js
> +/* eslint no-use-before-define: ["error", { "functions": false }] */
이 주석 이제 삭제해도 괜찮지 않을까요? ㅎㅎ

2022-08-08 06:20 UTC, merged