# Week 1 Assignment 1 - 'remove let'
CodeSoom/week1-assignment-1 pull request #193
Opened 2022-08-05 09:37 UTC by SangYoonLee1231

- <strong>월요일 아침</strong>부터 학습을 진행했으나, 부족한 기본기로 인한 느린 진도로 인해 이제서야 PR을 보내게 되었습니다..  
  (PR도 이번이 처음입니다.)

- 비록 많이 늦었지만 잘 부탁드립니다.

<br/>

### 과제 수행 방식
- 변수를 재할당해선 안 된다고 하였기에, <strong>매개변수를 이용하여 값을 넘겨주는 방식</strong>으로 과제를 수행했습니다.

2022-08-05 12:49 UTC, daadaadaah requested changes
늦어지만 이렇게 PR 날려주신 점 너무 잘하셨어요!👍
push 전에 lint와 test 한번 체크해주시면 좋을 것 같아요!ㅎㅎ
지금 test 에서 에러나고 있어요!

2022-08-05 12:49 UTC, daadaadaah commented on src/index.js
> +const count = 0;
count 변수가 56번째 줄에서만 사용해서 따로 변수화가 필요 없을 거 같아요!ㅎㅎ

2022-08-05 12:49 UTC, daadaadaah commented on src/index.js
> +function handleClick(count) {
render 함수에도 count 라는 이름을 사용하므로, 다른 네이밍으로 해주는게 좋을 것 같아요!ㅎㅎ

2022-08-05 13:25 UTC, SangYoonLee1231 commented
> 늦어지만 이렇게 PR 날려주신 점 너무 잘하셨어요!👍 push 전에 lint와 test 한번 체크해주시면 좋을 것 같아요!ㅎㅎ 지금 test 에서 에러나고 있어요!

저런.. 깜빡했군요. 죄송합니다. 리뷰해주신 내용 반영하여 다시 수정했습니다!

2022-08-06 11:45 UTC, daadaadaah requested changes
https://github.com/CodeSoom/react-week1-assignment-1/pull/193/commits/c2dc6c757ce9acb7bdbd8cc35988b34581a7968c 수정 전 코드인
handleClick 함수를 따로 빼서 사용하시는게 나중에 유지보수하기에 더 괜찮을 것 같아요!

2022-08-06 14:21 UTC, SangYoonLee1231 commented on src/index.js
> +render(0);
혹시 바보 같은 질문 하나만 여쭤도 될까요..?

count 변수를 초기화 할 때, 수정 전 코드처럼 render 함수의 매개변수에서 0을 할당하는 방식과, 수정 후 코드처럼 render 함수 호출 시
0을 넘겨주는 방식 중 어떤 코드가 가독성이 더 좋은 코드라고 말할 수 있을까요? 아님 그저 스타일의 차이라고 볼 수 있나요?

2022-08-08 02:25 UTC, daadaadaah approved these changes
수고하셨습니다👏

2022-08-08 02:25 UTC, daadaadaah commented on src/index.js
> +render(0);
초기값이 0으로 지정되어 있다면, 저는 수정 전 코드가 더 좋은 것 같아요!ㅎㅎ
왜냐하면, 함수가 선언된 부분만 보고서 초기값을 알 수 있기 때문에, 좀더 함수를 명확히 알 수 있기 때문이예요!

2022-08-08 06:20 UTC, merged