Remove let
CodeSoom/week1-assignment-1 pull request #198
Opened 2022-10-10 11:01 UTC by Sunset-Kim

to remove let, add state.
divide function, view

이번 PR에서 다음과 같은 작업을 수행했습니다.

1) let을 없애며 전역에 흩어진 기능과 변수와 함수를 render function으로 넣었습니다.
2) view를 분리했습니다.

2022-10-10 16:21 UTC, daadaadaah requested changes
월요일부터 PR 날려주신 점 너무 잘하셨어요!👍👍👍👍
남은 8주동안 같이 잘해봐요!🙇‍♀️

2022-10-10 16:21 UTC, daadaadaah commented on src/index.js
> +  const root = createElement('div', null, p1, p2);
`createElement`보다 좀더 간단하게 표현할 수 있는데, 아샬님은 어떻게 하셨는지 다시 한번 강의를 시청해봅시당!ㅎㅎ

2022-10-11 03:17 UTC, Sunset-Kim commented on src/index.js
> +  const root = createElement('div', null, p1, p2);
빨리 코드리뷰를 받고 싶어서 기본적인 내용을 누락했네요! 죄송합니다. 앞으로 8주간 잘 부탁드립니다 !

render 함수가 실행될때, 매번 생성되는 addcount, setcount를 mvc pattern 처럼 model controller 로 분리해서 작성하면 도움이 될까요?

2022-10-12 02:02 UTC, daadaadaah commented on src/index.js
> +  const container = document.getElementById('app');
맥락 구분을 위해 한줄씩 띄어줍시당!ㅎㅎ

2022-10-12 02:02 UTC, daadaadaah commented on src/index.js
> +  const root = createElement('div', null, p1, p2);
디자인 패턴 적용시켜보는 것도 좋지만, 아샬님 강의를 보면 디자인 패턴을 쓰지 않고도 코드를 간단히 표현하신 걸 알 수 있습니다!ㅎㅎ코드숨 교육기간동안 최대한 아샬님이 어떻게 코드를 작성하는지 잘 관찰하시고 자기꺼로 만들어보도록 해보는걸 추천드려요!ㅎㅎ

2022-10-12 02:02 UTC, daadaadaah commented on src/index.js
> +const template = (count, addCount, setCount) => (
render 밖으로 빼주셨는데, 안에서 관리했을 때와 비교하여 어떤 장점이 있나요?ㅎㅎ

2022-10-12 02:05 UTC, daadaadaah commented on src/index.js
> +  const addCount = (count) => { render({ ...state, count: count + 1 }); };
한줄로 간단히 써줄 수 있는데, 되도록 중괄호를 사용할 때에는 아래처럼 다음줄에 써주는게 가독성에 더 좋은 것 같아요!ㅎㅎ
```js
  const addCount = (count) => { 
      render({ ...state, count: count + 1 }); 
  };
```

2022-10-12 11:11 UTC, Sunset-Kim commented on src/index.js
> +const template = (count, addCount, setCount) => (
render 함수안에 단순히 view만 담당하는 부분은 분리해서 함수가 너무 길어지지 않게 하는 것이 좋겠다고 생각했습니다~

2022-10-12 11:12 UTC, Sunset-Kim commented on src/index.js
> +  const addCount = (count) => { render({ ...state, count: count + 1 }); };
넵 리뷰반영하겠습니다

2022-10-12 11:12 UTC, Sunset-Kim commented on src/index.js
> +  const container = document.getElementById('app');
넵 리뷰반영하겠습니다

2022-10-13 05:03 UTC, daadaadaah requested changes

2022-10-13 05:03 UTC, daadaadaah commented on src/index.js
> +const template = (count, addCount, setCount) => (
아는게 많으셔서 다양한 시도를 해보시는 것 같아요!👍👍👍 다양한 시도를 해보는 건 언제나 좋다고 생각합니다!
다만, 코드숨 교육기간 동안 아샬님이 한 방식으로 한번 따라해보시는건 어떠신가요?ㅎㅎ아샬님은 어떻게 만드셨느지 강의를 통해 알 수 있습니당!ㅎㅎ

2022-10-13 08:57 UTC, Sunset-Kim commented
앗 넵! 죄송합니다. 과제는 아샬님 방법 위주로 진행하겠습니다. 금일 저녁에 다시 리뷰 요청드리겠습니다.

2022-10-14 02:39 UTC, daadaadaah approved these changes
> 앗 넵! 죄송합니다. 과제는 아샬님 방법 위주로 진행하겠습니다. 금일 저녁에 다시 리뷰 요청드리겠습니다.

- 허걱! 오해는 없으셨으면 좋겠어요ㅠㅠSunse-kim님 코드가 틀렸다는 건 아니고! 코드숨 기간 동안에는 잘하는 아샬님의 방법을 한번 체화시켜보시는 걸 추천드리는거예요! 저는 성장하는 방법 중에 하나가 잘하는 사람의 좋은 점을 따라하는거라고 생각하거든요! 과제 수행하시느라 수고많으셨습니당! 과제2도 같이 뿌셔봐요👊

2022-10-14 05:52 UTC, Sunset-Kim commented
정말 감사합니다!

2022-10-16 23:45 UTC, merged