remove let
CodeSoom/week1-assignment-1 pull request #199
Opened 2022-10-11 08:44 UTC by yxxnhx

안녕하세요 과제를 하는데 계속 막히고 어디서부터 시작해야할지 모르겠어서 질문차 PR 남깁니다.
usestate를 써서 따로 선언을 하지 않고 풀어나가니 jsx가 아니고 hook을 이용하는 것이 이번 숙제의 취지가 아닌 것 같은데 그 방법 외에는 다른 방법이 떠오르지 않고 계속 막혀서 아무리 찾아도 어떤식으로 풀어나가야하는지 모르겠습니다.
hook이 아닌 자바스크립트로만 접근할 수 있는 다른 방식이 있을까요?

2022-10-12 02:13 UTC, daadaadaah commented
> 안녕하세요 과제를 하는데 계속 막히고 어디서부터 시작해야할지 모르겠어서 질문차 PR 남깁니다.
usestate를 써서 따로 선언을 하지 않고 풀어나가니 jsx가 아니고 hook을 이용하는 것이 이번 숙제의 취지가 아닌 것 같은데 그 방법 외에는 다른 방법이 떠오르지 않고 계속 막혀서 아무리 찾아도 어떤식으로 풀어나가야하는지 모르겠습니다.
hook이 아닌 자바스크립트로만 접근할 수 있는 다른 방식이 있을까요?

안녕하세요! 반가워요:) yxxnhx님😊
막막하셨지만, PR 먼저 날라주신 점 너무 잘하셨어요👍👍👍
hook이 아닌 자바스크립트로만 과제를 진행하실 수 있어요!
조금 힌트를 드리자면, `render 함수의 매개변수`를 잘 활용해보세요!ㅎㅎ

2022-10-12 02:13 UTC, daadaadaah commented on src/index.js
> +}
render 함수의 inner 함수로 선언해주시는건 어떠신가요?ㅎㅎ

2022-10-12 05:55 UTC, yxxnhx commented on src/index.js
> +}
네 한번 해보겠습니다!

2022-10-13 03:25 UTC, daadaadaah requested changes
> 근데 render 외부에서 initial로 count는 0이라고 초기선언을 해주었는데 render 하단에 count:0이라고 지정을 해주지 않으면 count는 정의되지 않았다는 오류가 뜹니다. 이 부분은 왜 그런 것일까요?

- 현재 작성해주신 코드를 보면, render "외부"가 아닌 "내부"에 initial로 count는 0이라고 선언을 해주셨습니다!ㅎㅎ그래서, render 호출시 count 초기값을 설정해주셔야 되요!ㅎㅎ[default function parameter](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Functions/Default_parameters) 활용해보셔두 되구요!ㅎㅎ코드를 작성하실 때, 이게 왜 이렇게 동작하지 라는 의문이 드실 때, console.log 하나하나 찍어보면서 확인해보는걸 추천드립니다!ㅎㅎ

2022-10-13 03:25 UTC, daadaadaah commented on src/index.js
> +  };
`initial` 변수는 언제 필요한 변수인가용?ㅎㅎ

2022-10-13 06:58 UTC, yxxnhx commented on src/index.js
> +  };
초기값을 잡아주려고 선언을 했었던 거였는데 기본값 매개변수를 이용해서 설정하면 될 것 같네요!! 한번 변경해보겠습니다

2022-10-13 07:10 UTC, yxxnhx commented
트레이너님께서 주신 기본값 매개변수를 이용하여서 initial 변수를 지우고 render 함수에서 초기값을 설정하여 변경해보았습니다
만약에 initial 변수를 바깥에서 사용하였다면 render 함수에서 호출 시에는 따로 초기값을 설정하지 않고도 사용이 가능한 것인가요?

2022-10-14 02:42 UTC, daadaadaah requested changes
> 만약에 initial 변수를 바깥에서 사용하였다면 render 함수에서 호출 시에는 따로 초기값을 설정하지 않고도 사용이 가능한 것인가요?

코드랑 같이 보여주시면, 답변에 도움될 것 같아요!😅

2022-10-14 02:42 UTC, daadaadaah commented on src/index.js
> +  }
`idx` 라는 변수명 보다 좀더 의도를 드러내는 단어는 없을까용?🤔

2022-10-14 10:24 UTC, yxxnhx commented on src/index.js
> +  }
넵 변경해보겠습니다

2022-10-14 10:25 UTC, yxxnhx commented
처음에는 이렇게 초기값을 정해줄 initial이 render 함수 안에 내부에 있었습니다
![code](https://user-images.githubusercontent.com/50559373/195825096-f5c7e10c-d93c-41bd-b739-8b0aea981055.png)

2022-10-15 03:06 UTC, daadaadaah commented
> 처음에는 이렇게 초기값을 정해줄 initial이 render 함수 안에 내부에 있었습니다 ![code](https://user-images.githubusercontent.com/50559373/195825096-f5c7e10c-d93c-41bd-b739-8b0aea981055.png)

- [yxxnhx](https://github.com/yxxnhx)님 생각하시기에, 55번째 줄이랑 21 ~23줄 둘다 초기화 해주는 걸로 이해하신건가용?ㅎㅎ

2022-10-15 03:08 UTC, daadaadaah approved these changes
수고하셨습니당!ㅎㅎ

2022-10-15 03:08 UTC, daadaadaah commented on src/index.js
> +  function handleClickNumber(clickNumber) {
다음 과제부터는 변수명 사용하실 때, `동사`보다는 `형용사`나 `수동태` 사용하는걸 추천드려요!ㅎㅎ
왜냐하면, 함수명이랑 변수명이랑 혼동을 줄 수 있기 때문이예요!ㅎㅎ

2022-10-15 07:24 UTC, yxxnhx commented on src/index.js
> +  function handleClickNumber(clickNumber) {
넵 다음 과제부터는 유의하여 변수명을 지어보도록 하겠습니다

2022-10-16 23:45 UTC, merged