1주차 과제 1 - let을 제거해보자
CodeSoom/week1-assignment-1 pull request #200
Opened 2022-10-11 09:54 UTC by sejineeee

## 내용
변수에 값을 재할당하지 않고 문제를 해결하기 위해서 const 키워드로 상수를 선언하고, 객체를 할당하였습니다.
객체는 재할당을 하지 않고, 내부 프로퍼티의 값을 변경할 수 있는 것을 이용하여 값을 변경하였습니다.

## 스크린샷

https://user-images.githubusercontent.com/86041335/195057785-4840011b-ec51-4547-9e11-7181f2b3ea3a.mov

## 질문
- `function`키워드를 이용하면 호이스팅이 되는 것으로 알고 있습니다. 하지만, 계속 eslint를 실행시켰을 때 `'render' was used before it was defined`라고 에러가 출력됩니다. 호이스팅이 되더라도 사용하기 전에 선언을 하는 것이 권장되는 방식인지 궁금합니다.

2022-10-12 02:24 UTC, daadaadaah requested changes
> function키워드를 이용하면 호이스팅이 되는 것으로 알고 있습니다. 하지만, 계속 eslint를 실행시켰을 때 'render' was used before it was defined라고 에러가 출력됩니다. 호이스팅이 되더라도 사용하기 전에 선언을 하는 것이 권장되는 방식인지 궁금합니다.
- function키워드를 이용하면 호이스팅이 되는데, 개발자마다 다르겠지만 저는 가독성과 유지보수측면에서는 사용하기 전에 선언하는 것이 경험상 더 좋았습니다!

2022-10-12 02:24 UTC, daadaadaah commented on src/index.js
> +};
객체는 `const`일 때도 수정 가능하다는 걸 이용해서 문제를 해결하려는 시도를 하셨군요!ㅎㅎ그런데, 객체 같은 외부 변수 없이 직접 수정이 가능한 형태로 만들어볼 수 있는 방법은 없을까요? 과제로 왜 `let`을 없애려고 하는지 한번 생각해봅시당!

2022-10-12 06:53 UTC, sejineeee commented on src/index.js
> +};
외부 변수 없이 직접 수정이 가능한 형태라는 의미를 잘 모르겠습니다. 함수 내에서 let이 아닌 const를 이용해서 지역변수를 선언하는 방향으로 해야 되는 것일까요?

2022-10-13 02:48 UTC, sejineeee commented
@daadaadaah [85892c1](https://github.com/CodeSoom/react-week1-assignment-1/pull/200/commits/85892c1a08e4f80ac1cb3272d8d5fa8911e386ba) 외부 변수 없이 직접 수정이 가능한 형태로 구현하기 위해 매개변수를 이용하여 수정해보았습니다. 다시 리뷰 부탁드립니다. 감사합니다.

아직 git 사용이 서툴러서 오류가 발생하여 force push를 하게 되었습니다. [ba95802](https://github.com/CodeSoom/react-week1-assignment-1/commit/ba958020f20dd447a65259b70811f7269384b8dd) 이전 커밋이니 참고하여 주시길 바라겠습니다.
다음부터는 유의하여 커밋하도록 하겠습니다! 감사합니다.

2022-10-13 03:28 UTC, daadaadaah commented on src/index.js
> +};
넹! 질문하실 때, 코드랑 같이 봐야 된다면, 셀프 코드리뷰 방식을 활용해서 코드에 코멘트를 달여주시면 더 좋을 것 같아요!ㅎㅎ

2022-10-13 03:32 UTC, daadaadaah approved these changes
github 문제 발생했을 때 당황하셨을텐대, 혼자 해결하신 점 너무 잘하셨어요👏👏👏
과제도 의도에 맞게 잘 수행하셨구요!ㅎㅎ과제2도 같이 화이팅해봐용👊

2022-10-13 12:02 UTC, sejineeee commented
[bc34117](https://github.com/CodeSoom/react-week1-assignment-1/pull/200/commits/bc34117a6294d5639002ea11352b37ca73fa2308) 이미 승인이 났으나, `count += 1`을 하지 않고 인자에 1을 더하는 방법으로 바꿔보았습니다. 그리고 `function` 키워드에서 화살표함수로 변경해보았습니다.
감사합니다!! 🥺

2022-10-16 23:45 UTC, merged