remove let
CodeSoom/week1-assignment-1 pull request #201
Opened 2022-10-12 11:01 UTC by hyeji07

### 내용
**assignment 1**

let을 사용하지 않는 과제를 수행하기 위해 const로 선언하여 객체를 생성했습니다.
click시 객체의 프로퍼티 값이 변경되도록 설정하였습니다.

### 스크린샷
![2022-10-12 19 49 33](https://user-images.githubusercontent.com/108104436/195324032-136413d7-be04-4679-94b9-2e9294dac258.gif)

### 질문
1. {Object.values(count)} 를 사용하여 화면에 출력되게 하였는데 방법이 맞는지 궁금합니다.
2. eslint를 실행시, function handleClick, function handleClickNumber 이 function render()외부에 위치하여 오류가 났습니다. 그래서 render의 안으로 넣었는데 이렇게 작성하는 것이 맞나요?
3. 코드의 방향성이 맞는지, 오류, 개선점 등이 궁금합니다.

2022-10-13 03:38 UTC, daadaadaah requested changes
> 1. {Object.values(count)} 를 사용하여 화면에 출력되게 하였는데 방법이 맞는지 궁금합니다.
- Object.values 를 사용하신 이유가 궁금합니당! 그냥 `{ count }`로 했을 때 문제가 발생하나용?ㅎㅎ

> 2. eslint를 실행시, function handleClick, function handleClickNumber 이 function render()외부에 위치하여 오류가 났습니다. 그래서 render의 안으로 넣었는데 이렇게 작성하는 것이 맞나요?
- 네, 잘하셨어요! 그런데, 오류가 났을 때는 어떤 오류가 났는지 이야기해주시거나 스샷 찍어주시면 더 좋을 것 같아요!ㅎㅎ 또한, 그 오류가 났을 때 왜 그 오류가 났는지에 대해 공부해보시면 더욱 좋습니당! 

> 3. 코드의 방향성이 맞는지, 오류, 개선점 등이 궁금합니다.
- 코멘트 남겨드렸어요!ㅎㅎ

2022-10-13 03:38 UTC, daadaadaah commented on src/index.js
> +};
객체는 `const`일 때도 변경할 수 있다는 점을 이용해서 문제를 해결하려는 시도를 하셨군요!ㅎㅎ그런데, 객체 같은 외부 변수 없이 직접 수정이 가능한 형태로 만들어볼 수 있는 방법은 없을까요? 과제로 왜 let을 없애려고 하는지 한번 생각해봅시당!

2022-10-13 09:43 UTC, hyeji07 commented on src/index.js
> +};
> Object.values 를 사용하신 이유가 궁금합니당! 그냥 { count }로 했을 때 문제가 발생하나용?ㅎㅎ

=>수정 전은 객체여서 {count}로 했을 시, 바로 값을 가져오지 못해 Object.values를 사용했습니다. 지금은 수정해서 {count}로도 적용이 됩니다!

> 코멘트

=>넵 리뷰반영하여 외부변수 대신 함수 render에 매개변수로 넣어 다시 올렸습니다!


> ### Q.

1. 수정한 코드에서 아래와 같은 오류가 발생하는데, 어떻게 해야하나요?
![image](https://user-images.githubusercontent.com/108104436/195561868-3dfc1d18-7595-483d-b5c9-088ed2214cff.png)


2. LF관련 오류가 뜨는데, 따로 하는 것 없이 두면 되나요?
![image](https://user-images.githubusercontent.com/108104436/195562279-b913e9e8-80ff-4742-bd81-27fb7453be7c.png)

2022-10-13 09:45 UTC, hyeji07 commented on src/index.js
> +};
> Object.values 를 사용하신 이유가 궁금합니당! 그냥 { count }로 했을 때 문제가 발생하나용?ㅎㅎ

=>수정 전은 객체여서 {count}로 했을 시, 바로 값을 가져오지 못해 Object.values를 사용했습니다. 지금은 수정해서 {count}로도 적용이 됩니다!

> 코멘트

=>넵 리뷰반영하여 외부변수 대신 함수 render에 매개변수로 넣어 다시 올렸습니다!

2022-10-13 09:45 UTC, hyeji07 commented
> ### Q.

1. 수정한 코드에서 아래와 같은 오류가 발생하는데, 어떻게 해야하나요?
![image](https://user-images.githubusercontent.com/108104436/195561868-3dfc1d18-7595-483d-b5c9-088ed2214cff.png)


2. LF관련 오류가 뜨는데, 따로 하는 것 없이 두면 되나요?
![image](https://user-images.githubusercontent.com/108104436/195562279-b913e9e8-80ff-4742-bd81-27fb7453be7c.png)

2022-10-14 10:56 UTC, daadaadaah requested changes

2022-10-14 10:56 UTC, daadaadaah commented on src/index.js
> +  function handleClickNumber(value) {
`value`보다 좀더 의도가 드러나는 단어로 표현해보는건 어떠신가요?ㅎㅎ

2022-10-14 10:56 UTC, daadaadaah commented on src/index.js
> +    number += 1;
이 줄 질문 주셨는데, 에러 메시지의 의미가 어떤 의미로 파악하셨나요?ㅎㅎ

2022-10-14 11:00 UTC, daadaadaah commented
> 2. LF관련 오류가 뜨는데, 따로 하는 것 없이 두면 되나요?
>    ![image](https://user-images.githubusercontent.com/108104436/195562279-b913e9e8-80ff-4742-bd81-27fb7453be7c.png)
>    (검색해보았을 때 mac과 윈도우 차이여서 git config --global core.autocrlf true 이걸 터미널에 작성하라는데 맞나요? 만약 작성한다면 협업시에도 문제가 없는지 궁금합니다. )

- 저 명령어를 입력하였는데도, 문제 해결이 안되었나용?ㅎㅎ

2022-10-15 07:15 UTC, hyeji07 commented on src/index.js
> +  function handleClickNumber(value) {
value 대신 number 로 수정하였습니다!

2022-10-15 07:25 UTC, hyeji07 commented
> git config --global core.autocrlf true 명령어를 입력하였는데도, 문제 해결이 안되었나용?ㅎㅎ
네..ㅠ 터미널에 작성 후 npm run lint 를 실행하자 아래와 같은 오류가 계속 있습니다
![image](https://user-images.githubusercontent.com/108104436/195974660-6a3a229e-81b4-428e-980c-c317056bff64.png)

2022-10-15 07:29 UTC, hyeji07 commented on src/index.js
> +    number += 1;
파라미터를 직접적으로 변경하여 생긴 오류같습니다..
아래와 같이 매개변수를 통해 변경되도록 수정하였습니다..!
`function handleClick(number) {
    render(number + 1);
  }`

2022-10-16 01:51 UTC, daadaadaah commented
> > git config --global core.autocrlf true 명령어를 입력하였는데도, 문제 해결이 안되었나용?ㅎㅎ
> > 네..ㅠ 터미널에 작성 후 npm run lint 를 실행하자 아래와 같은 오류가 계속 있습니다
> > ![image](https://user-images.githubusercontent.com/108104436/195974660-6a3a229e-81b4-428e-980c-c317056bff64.png)

개발환경과 관련된 거라서, 개발 환경 셋팅하신 윤석님께 한번 물어보고 답변드리게요!ㅎㅎ

2022-10-16 04:35 UTC, hyeji07 commented
> 개발환경과 관련된 거라서, 개발 환경 셋팅하신 윤석님께 한번 물어보고 답변드리게요!ㅎㅎ
혹시, git config --global core.autocrlf true 입력했을 때, 어떤 에러 메시지 같은건 없었나요?

공부방에서 윤석님께 도움받아 git config --global core.autocrlf input  를 통해 문제 해결했습니다! 감사합니다~

2022-10-16 23:44 UTC, daadaadaah approved these changes

2022-10-16 23:44 UTC, daadaadaah commented
> > 개발환경과 관련된 거라서, 개발 환경 셋팅하신 윤석님께 한번 물어보고 답변드리게요!ㅎㅎ
> > 혹시, git config --global core.autocrlf true 입력했을 때, 어떤 에러 메시지 같은건 없었나요?
> 
> 공부방에서 윤석님께 도움받아 git config --global core.autocrlf input 를 통해 문제 해결했습니다! 감사합니다~

오! 역시 윤석님이 짱입니당👍 다음 과제도 같이 힘내봅시당!👊

2022-10-16 23:45 UTC, merged