Remove let variable
CodeSoom/week1-assignment-1 pull request #202
Opened 2022-12-06 11:46 UTC by KwangMin-Moon

2022-12-06 14:06 UTC, daadaadaah requested changes
빠르게 PR 올려주신 점 너무 좋습니다!ㅎㅎ
앞으로 8주동안 잘해봅시당👊

2022-12-06 14:06 UTC, daadaadaah commented on src/index.js
> +function handleClick(count) {
render 함수 내부에서 관리하는 거랑 이렇게 외부에서 관리하는 거랑 어떤 차이가 있을까요?ㅎㅎ

2022-12-07 11:15 UTC, KwangMin-Moon commented on src/index.js
> +function handleClick(count) {
안녕하세요 트레이너님:) 
8주 동안 잘 부탁드립니다 ㅎㅎ

내부에서 관리한다는 생각을 못했는데 내부에 넣을 수도 있었네요 
외부에서 관리하면 다른 곳에서도 활용할 수 있다는 장점이 있을거 같아요
내부에서 관리하면 함께 호출하는 button 태그와 한 함수 안에 있어서 코드가 복잡해질 때 관리하기 쉬울 거 같아요

2022-12-08 06:35 UTC, daadaadaah commented on src/index.js
> +function handleClick(count) {
내부에서 관리한다는 의미는 render의 매개변수가 아니라, 내부 함수로 선언한다는 의미였어요!ㅎㅎ혹시, 한번 해보시겠어요?ㅎㅎ

2022-12-08 06:36 UTC, daadaadaah commented on src/index.js
> +function handleClick(count) {
내부에서 관리한다는 의미는 render의 매개변수가 아니라, 내부 함수로 선언한다는 의미였어요!ㅎㅎ혹시, 한번 해보시겠어요?ㅎㅎ

2022-12-26 12:00 UTC, merged