Remove let
CodeSoom/week1-assignment-1 pull request #204
Opened 2022-12-08 10:03 UTC by naji0001

1. 카운팅 숫자를 매개변수로 전달
2. 버튼 클릭 이벤트 리스너를 render내부에서 선언

2022-12-09 09:22 UTC, daadaadaah requested changes

2022-12-09 09:22 UTC, daadaadaah commented on src/index.js
> +  }
1. value보다 좀더 의도가 드러나는 표현은 없을까요?
2. `handleClick` 보다 좀더 의도가 드러나는 표현은 없을까요?

2022-12-09 10:23 UTC, naji0001 commented on src/index.js
> +  }
수정하였습니다 :)

2022-12-11 11:14 UTC, daadaadaah commented on src/index.js
> +  function changeNumber(number) {
`increase`도 `change`의 의미를 갖고 있어서 `changeNumber`보다 좀더 나은 표현은 없을까요?ㅎㅎ

2022-12-26 12:00 UTC, merged