Use function [getCount] and [setCount] instead of 'let count'
CodeSoom/week1-assignment-1 pull request #34
Opened 2020-09-14 13:01 UTC by juunini

`handleClick`과 `handleClickNumber`에서 `render` 함수를 사용하는 것이
eslint에서 정의되기 전 사용된다는 경고 때문에 매번 `render`를 하는 대신
`setCount` 함수를 통하여 Click me! 안에 있는 숫자만 변경하도록 수정했습니다.

그리고, `let count = 0;`를 없애기 위해 `getCount`와 `setCount` 함수로 대체했습니다.

마지막으로, `Click me!` 다음 괄호를 쓸 때 줄바꿈이 되는 부분을 방지하기 위하여  
```javascript
/* eslint-disable react/jsx-one-expression-per-line */
```
내용을 추가했습니다.
(과제 1 안내에 ESLint config를 전역적으로 쓰는것이 좋지 않다고 하셔서 파일 상단에 추가하였습니다.)

2020-09-14 13:14 UTC, juunini commented on src/index.js
> +}
아.... 화장실 갔다오고 다시 보니 이렇게 했을걸 하는게 생각나서 올려봅니다 ㅠㅠ

```javascript
const count = {
  value: 0,

  get: () => count.value,
  set: (value) => {
    count.value = value;

    document.getElementById('count').innerText = value;
  },
};
```

2020-09-14 13:49 UTC, hannut91 commented on src/index.js
> +}
벌써 2가지 해결법을 시도하셨군요!
`count`를 `const`로 선언하셔서 값을 변경하는 메서드들을 추가해서 문제를 해결하셨네요 ㅎㅎ

`count`객체 자체는 재할당할 수 없어 변경할 수 없지만, `count`의 `value`는 변경할 수 있는 것을 이용해서 문제를 풀어주셨네요. count가 변경이 되기 때문에 언제 어떻게 변하는지 파악하기 어려울 수 있지만 `getter`와 `setter`로 일관성을 가지도록 하신게 보이는데요. 이번 과제의 의도에 대해서 조금 더 생각해보시면 좋을 것 같아요. 단순히 `let`대신에 `const`를 사용하는 이유가 문법적인 이유가 아니라 다른 이유가 있어요

2020-09-14 13:49 UTC, hannut91 commented on src/index.js
> +  return parseInt(document.getElementById('count').innerText, 10);
DOM객체에 접근하여 문제를 해결하셨네요. DOM객체 직접 접근하는 것은 우리에게 많은 일을 가능하도록 기능들을 제공하지만 그만큼 사용하기 어렵다는 단점이 있어요. 그리고 해당 값을 접근하는 방법이 어디서는 접근 가능하기 때문에 추적이 어려운 이유도 있고, 또 우리는 어떤 상태에 대해서 어떻게 보여줄지를 결정하고 싶은데 DOM은 그 반대에요. 지금은 DOM에서부터 상태를 얻고 상태를 다시 DOM에 반영하고 있죠. 

우리는 특정한 상태를 가지고 있고 그 상태를 가지고 화면에 보여주도록 수정해보시면 좋을 것 같아요

2020-09-14 14:19 UTC, juunini commented on src/index.js
> +  return parseInt(document.getElementById('count').innerText, 10);
만약 이렇게 쌩으로 풀어서 jsx를 작성하는게 아니라, create-react-app 을 했으면 컴포넌트와 모듈을 각각 작성했겠지 하고 생각해보니

let을 제거해보라는 과제는 단순히 이런 방법 저런 방법을 고민해보라는 것이 아니라, 관심사의 분리에 대해 생각해보라고 주신 과제가 아닐까 하는 생각이 들었습니다.

- count의 값을 관리하는 관심사
- 화면에 숫자와 버튼을 랜더링해주는 관심사
- 분리된 두 관심사를 묶어서 사용하는 코드(결론적으로 재사용이 가능해짐)

내일은 이렇게 작성하여 다시 커밋해보겠습니다.

2020-09-15 00:45 UTC, juunini commented
모듈, 컴포넌트, 컨테이너 형식으로 분리시켜 보았습니다.
컴포넌트 형식으로 분리시키니, 기존에 `[1, 2, 3]` 넣던 부분의 하드코딩을 벗어날 수 있게 되어서
`[30, 60, 100]` 의 케이스를 추가시켰고, 그에 따라 테스트 케이스도 추가하였습니다.

숫자를 표시하는 부분에 대해 의존성을 주입받게 하기 위해 변수로 할당했는데
ESLint를 잡기 위해 `// eslint-disable-next-line no-param-reassign` 를 써야하는 것을 보고
타입스크립트였으면 이럴 필요가 없지 않았을까 하는 생각이 들었습니다.

2020-09-15 13:09 UTC, juunini commented
아샬님의 힌트를 듣고나서 제가 혼자 이상하고 복잡하게 오해하고 있었던 것 같아서
첫 샘플 코드로 돌아간 뒤 `let count` 를 없애는데에만 충실하게 변경해보았습니다.
(`render` 함수 선언 시 `count`를 입력받는 형태로 변경했습니다.)

`handleClick`과 `handleClickNumber` 에서 `render`를 사용할 때 ESLint 에러를 피하기 위해
`no-use-before-define */`를 추가하였습니다.

2020-09-15 15:59 UTC, hannut91 requested changes
고민을 많이하셔서 과제의 의도를 정확하게 파악하신 다음에는 바로 해결책을 찾으셨네요 ㅎㅎ
eslint룰만 disable하지 않고 해결해보세요

2020-09-15 15:59 UTC, hannut91 commented on src/index.js
> +/* eslint-disable react/jsx-one-expression-per-line, no-use-before-define */
eslint에서 `no-use-before-define`룰 때문에 통과가 안되서 추가하셨군요. `no-use-before-define`룰을 disable해서 추가하기 보다는 이 룰이 왜 적용되는지 생각해보시면 좋을 것 같아요 ㅎㅎ 그리고 disable없이 문제를 해결하려다 보면 자연스럽게 더 나은 코드를 작성하도록 노력하게 됩니다.

See also
  - https://eslint.org/docs/rules/no-use-before-define

2020-09-15 15:59 UTC, hannut91 commented on src/index.js
> +}
함수 이름이 숫자를 클릭했을 때 다루는 함수니까 `value`대신에 `number`를 사용하는건 어떨까요? `value`는 사실상 아무런 의미가 없는 이름이라서 `number`로 표현해줘도 좋을 것 같아요.

2020-09-16 04:58 UTC, juunini commented on src/index.js
> +}
변수명 부분은 저도 할까말까 고민했었던 부분인데 딱 집어주셨네요 :)
결국 숫자를 입력받아서 그대로 적용한다는 의미니까 말씀해주신대로 number로 변경하였습니다.

그리고, `no-use-before-define` 부분은 해당 함수 내에서 재귀함수로 호출하니 해결이 되더군요
해결 과정에서 새로운 배움이 있었습니다!

2020-09-16 14:58 UTC, hannut91 approved these changes
고생하셨습니다! 과제의 의도를 정확히 파악하셨고, 코드도 훌륭하네요!

2020-09-16 14:59 UTC, merged