Update src/index.js - render function
CodeSoom/week1-assignment-1 pull request #35
Opened 2020-09-14 13:15 UTC by koremp

기본 소스코드를 작성했습니다.

2020-09-14 13:21 UTC, hannut91 commented
시작이 좋습니다! ㅎㅎㅎ 풀리퀘스트 내용에 상세하게 어떤 작업을 했는지 상세한 내용을 적어주시면 더 좋을 것 같아요! 
제가봤을 때는 카운터 앱을 렌더 하는 기능과 버튼을 클릭했을 때 핸들러 함수를 구현하신 것 같네요

2020-09-14 13:27 UTC, koremp commented
createElement 함수를 작성했습니다.

2020-09-15 13:50 UTC, koremp commented
let 대신 counter 객체로 만들어보았지만 재할당 없이 해결할 수 있는 방법에 대해 감이 오지 않아요! ㅠㅠ

2020-09-15 16:31 UTC, koremp commented
전역변수 대신 함수 인자로 불변성을 가질 수 있다는 것이 너무너무 신기했고 이 방법을 왜 몰랐는지 싶을 정도로 상상 밖의 일이었어요. 아직 1주차 과제 1을 끝낸 것이지만 벌써 많은 것을 얻은 것 같네요.

2020-09-16 00:59 UTC, hannut91 requested changes
벌써부터 깨달음을 얻으신 것 같아서 좋네요 ㅎㅎ eslint룰과 변수이름에 대해서 조금 더 고민해보시면 좋을 것 같아요

2020-09-16 00:59 UTC, hannut91 commented on src/index.js
> +/* eslint-disable react/react-in-jsx-scope, react/jsx-filename-extension, no-use-before-define */
`no-use-before-define`룰을 disable없이 문제를 해결해보세요. eslint룰은 지키려고 노력하시면 자연스럽게 좋은 코드를 작성하려는 노력을 하게돼서 좋습니다. 왜 선언하기전에 사용하면 안좋다는거지? 를 고민해보시면 좋을 것 같아요

See also
  - https://eslint.org/docs/rules/no-use-before-define

2020-09-16 00:59 UTC, hannut91 commented on src/index.js
> +}
매개변수로 받은 값을 그대로 render함수로 넘겨주도록 작성하신것 같아요. `value`라는 이름은 변수이름자체가 표현해주는게 아무것도 없어요. value는 문자열이 될 수 있고 객체가 될 수 있고 배열이 될 수 있죠.

만약 `value` 대신에 `number`라는 이름을 사용하면 어떤 효과가 있을까요?

2020-09-16 05:23 UTC, koremp commented on src/index.js
> +}
타인이 코드를 읽었을 때 명시적인 코드가 되겠군요

2020-09-16 15:10 UTC, hannut91 approved these changes
문제의 의도를 잘 파악하셨고 굉장히 단순하게 문제를 해결하신 것 같아요! 좋네요 ㅎㅎ

2020-09-16 15:10 UTC, hannut91 commented on src/index.js
> +        <button type="button" onClick={() => { render(count + 1); }}>
버튼을 클릭했을 때 단순하게 render만 하면 되기 때문에 이렇게 문제를 해결해주신 것 같아요 ㅎㅎ 만약에 복잡한 로직이 들어가거나 하면 핸들러 함수를 사용하는게 더 표현력이 좋습니다. 만약 핸들러 함수를 사용하면서도 `no-use-before-define`를 피하고 싶으시다면

```js
function render(count) {
  function handleClick() {
    render(count + 1);
  }

  function handleClickNumber(number) {
    render(number);
  } 

  const element = (
    ...
  );
}
```

이런식으로 render함수안에 선언하면 eslint에서 에러가 나지 않습니다

2020-09-16 15:11 UTC, merged