[Week1] Remove let
CodeSoom/week1-assignment-1 pull request #37
Opened 2020-09-15 01:52 UTC by goodzzong

안녕하세요! 

여러가지 생각나는 대로 일단 변경해 보았습니다.
전체적으로 전역 변수를 제거하는 방향으로 수정하였습니다.

- [x] let 을 const 로 변경

- [x] 전역 변수 제거

- [x] 클래스 형태로 변경

2020-09-15 15:12 UTC, wholemann commented on src/index.js
> +    console.log('this.data', this.data);
console은 제거해주세요.

2020-09-15 15:19 UTC, wholemann commented on src/index.js
> +  $target = null;
$은 jquery에서 사용하는 컨벤션입니다. 지금은 사용하실 필요가 전혀 없습니다.

여담이지만 최신 자바스크립트는 private filed를 지원합니다.

- https://javascript.info/private-protected-properties-methods#private-waterlimit

2020-09-15 15:21 UTC, wholemann requested changes
변수에 재할당을 하는 방식은 이번 과제 방향에서 벗어나게 됩니다.

let을 사용하지 않고 재할당 없이 목적을 달성하려면 어떤 방법이 있을까요?

주어진 기존 코드에서 생각해보시면 좋을 겁니다. Class를 사용하면 재할당을 하지 않고 가능할까요?

2020-09-16 00:14 UTC, goodzzong commented on src/index.js
> +  $target = null;
새롭게 알았네요!
감사합니다

2020-09-16 01:28 UTC, goodzzong commented
let을 사용하지 않는 것과 재할당 하지 않기 위해 render 내부에서 처리하게 변경 하였습니다.
생각해보니 "이걸 왜 해야 할까?" 라는 고민을 하지 않고 이것 저것 시도 한 것 같습니다.

조언 감사합니다.

2020-09-17 01:07 UTC, wholemann commented on package.json
> +    "@babel/plugin-proposal-class-properties": "^7.10.4",
이건 이제 필요가 없을 거에요.

2020-09-17 01:07 UTC, wholemann commented on babel.config.js
> +  plugins: ['@babel/plugin-proposal-class-properties'],
빼주세용~

2020-09-17 01:08 UTC, wholemann commented on src/index.js
> +        <button type="button" onClick={() => handleClick(count)}>
```suggestion
        <button type="button" onClick={handleClick}>
```
이렇게 변경하셔도 됩니다.

2020-09-17 01:08 UTC, wholemann commented on src/index.js
> +function render(count = 0) {
count외에 여러 상태를 전달하고 싶으면 어떻게 개선해야 할까요?

2021-01-17 12:52 UTC, merged