Use count object to remove let keyword
CodeSoom/week1-assignment-1 pull request #38
Opened 2020-09-15 02:38 UTC by oceanide2

"쓰레기를 쓰겠다는 생각"으로 처음 보냅니다.

- 동영상 강의 내용이 쉽지 않다는 것을 느꼈고, DOM을 전혀 이해하지 못한다는 생각이 들었습니다.
- createElement 함수의 내용은 정확히 이해하지는 못했고, 소스에서 단순히 let을 어떻게 없애볼까만 생각해봤습니다.

2020-09-15 06:38 UTC, oceanide2 commented
- 함수 인자로 count값을 넘기는 방식으로 let을 없애 보는 것으로 수정해보려고 합니다. 이게 맞는 방향일까요?
- 개발자 도구의 element탭을 확인해보면 className="greetting"이 적용이 안되는데 이유를 잘 모르겠습니다.

2020-09-15 15:53 UTC, oceanide2 commented
- 처음에는 let을 없애기 위해서 count 객체를 선언하고 handleClick과 handleClickNumber에서 count 객체의 value 프로퍼티를 직접 접근하는 방식으로 생각했습니다. 
-  두번째로는 count 객체에 setValue와 increment 메서드를 선언하여 handleClick과 handleClickNumber함수에서 해당 메서드를 호출하는 방식으로 생각했습니다.
- 세번째로는 react 튜토리얼 내용을 살펴보다가 count 객체의 value 상태를 업데이트 하는 함수를 사용하는 방식으로 변경하였습니다.

2020-09-15 16:12 UTC, hannut91 requested changes
다양한 시도를 하면서 문제를 해결하려는 열정이 인상적이네요 ㅎㅎ 각각 방법을 바꿨을 때 서로 어떤 차이가 있는지 살펴보시면 좋을 것 같아요 ㅎㅎ

const로 선언한 객체는 직접 재할당 할 수 없지만 객체의 속성들은 할당할 수 있는 것을 이용해서 문제를 해결하셨네요.
하지만 여전히 속성에는 값이 재할당되고 있습니다. 이러면 이 속성은 언제 어디서 변하는지 예측하기 어렵습니다. 그래서 자연스럽게 코드의 예측가능성이 낮아지게 됩니다.

그리고 render함수에서는 함수 바깥의 변수에 접근하다보니 테스트가 어려워지고 이또한 코드가 어떻게 동작할지 가늠하기가 어려워요. render함수가 내부의 변수로만 동작한다면 외부 환경에 의해 render함수가 변하지 않기 때문에 동작한다면 테스트가 쉬워지고 어떻게 동작할지 예상하기 쉬워질거에요.

2020-09-15 16:12 UTC, hannut91 commented on src/index.js
> +/* eslint no-use-before-define: ["error", { "functions": false}] */
`no-use-before-define`룰을 disable하지 않고 문제를 해결해보세요. 왜 이룰을 사용하는지 생각해보시면 도움이 되실 것 같습니다. eslint룰을 강력하게 하고 지키려는 연습을 하다보면 더 나은 코드를 작성하려는 노력이 자연스럽게 됩니다.

See also
  - https://eslint.org/docs/rules/no-use-before-define

2020-09-16 11:18 UTC, oceanide2 commented
count 객체를 삭제하고 render함수에 파라미터를 전달하는 방식으로 변경하였습니다.
no-use-before-define 룰을 제거하려고 생각하다가 handleClick과 handleClickNumber 핸들러는 render 함수 내부로 이동하고 화살표 함수를 사용하였습니다. 

[질문사항] 
- 이 문제에 대해서 처음 고민했을 때, render 함수에 파라미터를 전달하는 것은 배제하고 생각했습니다. 전달할 수는 있겠지만 render함수에는 파라미터를 전달하지 않는 방식이 더 좋은게 아닌가로 생각했습니다. 마지막 수정에서 render함수에 파라미터를 전달하고 핸들러 함수도 모두 render 함수 내부로 이동했습니다. 이 방식이 과연 올바른 접근 방식인가요? 
- className="greeting" 이 적용되지 않는 이유를 잘 모르겠습니다.

2020-09-16 15:27 UTC, hannut91 requested changes
render함수에 파라미터를 전달하지 않는 방식이 더 좋다고 생각하신 이유가 궁금합니다 ㅎㅎ 

제 생각에는 render함수에 파라미터를 전달하지 않고 외부의 변수에 의존하게 되면 먼저 테스트가 굉장히 어려워지고, 외부의 변수가 어떻게 변할지 예측하기 어렵기 때문에 코드의 예측가능성이 굉장히 낮아지게됩니다. render 함수가 매개변수에 의해서만 달라진다면 테스트가 쉬워지고, 코드가 예측하기가 쉬워지는 장점이 있습니다.

className="greeting" 이 적용되지 않는 이유는 저희의 `createElement`함수에서 적절히 처리를 해주지 않아서 그렇습니다.

2020-09-16 15:27 UTC, hannut91 commented on src/index.js
> +  const handleClickNumber = (number) => render(number);
화살표 함수를 사용해서 핸들러 함수를 만드신 것 같아요. 화살표 함수는 중괄호로 감싸지 않으면 바로 실행한 결과가 반환이 됩니다. 그래서 지금 해당 코드만 보면 사실 핸들러 함수가 `render`함수를 실행한 결과를 반환하는 것처럼 보입니다.

하지만 의도하신대로 사실은 숫자를 입력받고 아무것도 반환하지 않는 함수여야 합닏나. 지금은 근데 화살표 함수를 사용해서 마치 함수가 무언가를 반환하는 것 처럼 보입니다. 그래서 이 함수는 아무것도 반환하지 않는 다는 것을 더 명확하게 표현하기 위해

```js
const handleClick = (number) => {
  render(number + 1);
}
```

이렇게 표현해주는게 더 좋을 것 같아요

2020-09-16 15:27 UTC, hannut91 commented on src/index.js
> +function render(countNumber) {
`count`라는 이름이 이미 숫자라는 의미를 내포하고 있어서 `Number`라는 이름을 붙이지 않아도 괜찮을 것 같아요

2020-09-16 15:27 UTC, hannut91 commented on src/index.js
> +  const handleClick = (number) => render(number + 1);
`handleClick`핸들러 함수로 `countNumber`를 넘겨줘서 동작하도록 만드신 것 같아요. 
render함수 안에서 handleClick이라는 함수가 만들어질 때 `countNumber`는 이미 함수 안에 캡쳐되어 변하지 않으므로 

```js
const handleClick = () => {
  render(countNumber + 1);
}
```

해줘도 여전히 순수한 함수라서 괜찮습니다.

2020-09-17 06:43 UTC, oceanide2 commented
앞서 말씀하신 것처럼 수정했습니다.
 제가 자바스크립트 관련 코드를 많이 본 것은 아니지만 render함수라고 이름이 붙여진 함수에는 파라미터가 없어 보여서 무의식중에 그렇게 생각했던 것 같습니다. 자세히는 잘 모르겠습니다만, 앞에서 말씀해주셨던 handleClick함수의 파라미터를 없애도 되는 경우와 비슷하지 않을까 생각됩니다. 
제가 언뜻 본 코드들이 render가 호출되는 시점에 관련 변수들이 이미 변하지 않도록 작성이 되어 있었기 때문이 아니였을까 정도로요.

2020-09-17 14:57 UTC, hannut91 approved these changes
리뷰에 대한 피드백을 착실히 잘 반영해주셨네요 ㅎㅎ 맨 처음 코드와 지금 코드와 비교했을 때 어떤 점이 달라졌나요?

2020-09-17 14:57 UTC, hannut91 commented on src/index.js
> +function render(count) {
render 함수에 기본값을 넣어줘도 되고 혹은 기본값을 가지도록 만들수도 있습니다.

```js
function render(count = 0) {
  ...
}
```

2020-09-17 14:57 UTC, hannut91 commented on src/index.js
> +    render(count + 1);
`count + 1`이 1을 더한 값을 충분히 나타내고 있기 때문에 상관없지만 만약 로직이 충분히 드러낸다고 생각하지 않으시면 Extract variable 리팩터링을 할 수도 있습니다. 참고용으로만 봐주시면 좋을 것 같아요

See also
  - https://github.com/hannut91/refactoring-practice/tree/master/6.3-extract-variable
  - https://refactoring.com/catalog/extractVariable.html

2020-09-17 14:57 UTC, merged