let 변수를 제거하기
CodeSoom/week1-assignment-1 pull request #40
Opened 2020-09-15 08:21 UTC by bbhye1

let을 const변수로 변경하는 대신 오브젝트로 만들어서 value값을 받아서
사용할 수 있게 했습니다.

그런데 eslint를 돌릴때마다 전체적으로 모든 줄에서Expected linebreaks to
be 'LF' but found 'CRLF'.eslintlinebreak-style) 오류가 납니다. 문제가
없어보이는데 이렇게 오류가 떠서 이 오류는 어떻게 해결해야하는지
궁금합니다.

2020-09-15 16:07 UTC, hannut91 requested changes
const로 선언한 객체는 직접 재할당 할 수 없지만 객체의 속성들은 할당할 수 있는 것을 이용해서 문제를 해결하셨네요.
하지만 여전히 속성에는 값이 재할당되고 있습니다. 이러면 이 속성은 언제 어디서 변하는지 예측하기 어렵습니다. 그래서 자연스럽게 코드의 예측가능성이 낮아지게 됩니다.

그리고 `render`함수에서는 함수 바깥의 변수에 접근하다보니 테스트가 어려워지고 이또한 코드가 어떻게 동작할지 가늠하기가 어려워요. render함수가 내부의 변수로만 외부 환경에 의해 render함수가 변하지 않기 때문에 동작한다면 테스트가 쉬워지고 어떻게 동작할지 예상하기 쉬워질거에요.

2020-09-15 16:07 UTC, hannut91 commented on src/index.js
> +/* eslint-disable no-use-before-define */
`no-use-before-define`룰을 disable하지 않고 문제를 해결해보세요. 왜 이룰을 사용하는지 생각해보시면 도움이 되실 것 같습니다. eslint룰을 강력하게 하고 지키려는 연습을 하다보면 더 나은 코드를 작성하려는 노력이 자연스럽게 됩니다.

See also
  - https://eslint.org/docs/rules/no-use-before-define

2020-09-15 16:07 UTC, hannut91 commented on src/index.js
> +/* eslint-disable react/button-has-type */
`react/button-has-type`이 룰도 disable없이 문제를 해결해보세요. 왜 `<button>` 태그에 type을 명시하라고 권고하는 것일까요?

2020-09-16 02:00 UTC, bbhye1 commented on src/index.js
> +/* eslint-disable react/button-has-type */
button은 submit이라는 속성을 기본값으로 가지고 있습니다 그렇기 때문에 type을 명시하지 않으면 브라우저에서 form submit 기능을 실행합니다. 하지만 여기서 필요한건 submit 기능이 아닌 button 안에 있는 숫자를 변경하는 기능이므로  자바스크립트를 실행해주는 type="button"을 명시해주어야 합니다. 

이것에 대해 찾다보니 기본적이고 간단한 것이지만 의문을 가지지않고 쉽게 지나쳐버린 게 많은것 같습니다. 앞으로의 과제에서도 좀 꼼꼼히 봐야할것같습니다!

2020-09-16 02:22 UTC, bbhye1 commented
no-use-before-define룰과 react/button-has-type룰을 disable 하지 않고 작성하기 위해  button에 button속성을 추가했고 버튼 함수들을 render함수 안의 최상단으로 넣어주었습니다.

  또 재할당을 하지 않게끔 변수를 선언해주는것이 아닌 render함수안에서 클릭함수들을 통해 직접 숫자를 변경해주도록 했습니다. 클릭함수들은 모두 render함수를 호출하고 그에 따라 DOM에 숫자들을 변경해주는 것이므로 클릭함수들을 변수의 값을 재할당하는 것이 아닌 render의 파라미터값을 조정해서 render의 number를 직접적으로 변경해주는 기능으로 만들었습니다.    

모든 변수와 함수들이 render함수 안에서 이루어지도록 해서 외부의 영향을 받지 않게 했습니다.

2020-09-16 02:39 UTC, bbhye1 commented on src/index.js
> +/* eslint-disable no-use-before-define */
호이스팅 때문이군요. eslint룰을 열심히 지키도록 노력하겠습니다!   그런데 "use strict"를 사용하는것과 eslint 모듈을 사용하는것의 차이점이 궁금합니다. 찾다보니 use strict는 ES5에서 지원을 하고 ES6부터는 디폴트가 strict mode이기 때문에 사용할 필요가 없다고 하는데 제가 처음 자바스크립트를 배웠을때는 use strict를 사용을 권장했었습니다.  지금 현업에서는 use strict를 사용하지 않나요??

2020-09-16 02:43 UTC, hannut91 commented on src/index.js
> +/* eslint-disable no-use-before-define */
현업에서 명시적으로 `use strict`를 사용하지는 않아요. 대부분 코드들을 모듈로 관리하기 때문에 모듈을 사용하면 항상 `use strict`로 동작하기 때문인 것 같아요.

![image](https://user-images.githubusercontent.com/14071105/93286295-e21e7200-f811-11ea-894a-cde8a453ff7d.png)

See also
  - https://ko.javascript.info/modules-intro#ref-2126

2020-09-16 03:12 UTC, bbhye1 commented on src/index.js
> +/* eslint-disable no-use-before-define */
그렇군요! 감사합니다!

2020-09-16 15:37 UTC, hannut91 requested changes

2020-09-16 15:37 UTC, hannut91 commented on src/index.js
> +  };
number가 falsy이면, 즉 null이나 undefined이면 1이고 아니면 1을 더하게 만드신 것 같아요. 이런 경우 number가 null이나 undefined가 되기 때문에 복잡하게 예외처리를 해줘야 한다는 건데요. number의 기본 값을 0으로 하면 어떨까요?

2020-09-16 15:37 UTC, hannut91 commented on src/index.js
> +          {number || 0}
number가 null이나 undefined가 안된다고 가정하면 이 코드가 더 간단해질 수 있을거에요

2020-09-16 15:37 UTC, hannut91 commented on src/index.js
> +  };
`value`라는 말은 아무런 의미를 나타내지 않아요. undefined를 나타낼때도 value를 사용할 수 있고 null을 나타낼때도, 문자열, 객체 등등을 나타낼때도 `value`를 사용할 수 있어서 아무런 의미가 드러나지 않습니다. 

현재 함수가 `handleClickNumber`이고 `render`함수가 필요하는 값이 무엇인지 드러낼 수 있도록 하려면 어떤 이름이 좋을까요?

2020-09-17 01:03 UTC, bbhye1 commented
handleClick함수는 숫자카운트를 하나씩 올려주는 함수이고 handleClickNumber는 숫자 자체를 넣어주는 함수이기때문에  handleClick함수의 변수명이 count이고  handleClickNumber함수의 변수명이 number가 되어야 한다고 생각해 변경해주었고 render함수의 변수도 count로 지정해주어 handleClick함수에서 숫자카운트를 올리는것을 가능하게 했습니다. 또 기본 값으로 0을 넣어주어서 예외처리가 없도록 했습니다.

2020-09-17 15:02 UTC, hannut91 approved these changes
리뷰에 대해서 잘 반영해주신것 같아요. ㅎㅎ 처음 코드랑 비교했을 때 어떤 변화가 일어났나요?

2020-09-17 15:02 UTC, hannut91 commented on jsconfig.json
> +}
여기 빈줄이 추가되었네요 ㅎㅎ 

![image](https://user-images.githubusercontent.com/14071105/93488854-c4e8c100-f941-11ea-974f-ed2194f0a749.png)

마지막 라인에 빈 줄을 하나 추가하라는 컨벤션입니다. 만약 마지막 라인에 빈줄이 없는 경우에 밑에 새로운 코드를 작성했을 때는 깃은 이렇게 변경사항을 보여줍니다.


```suggestion
}

doSomething();
```

사실은 밑에 `doSomething()`만 추가했는데 마치 `}`라인도 수정한 것 처럼 보이죠. 왜냐하면 `}`옆에 빈 줄을 나타내는 문자열도 들어갔기 때문이에요. 만약 빈줄이 추가되어있었다면 아래에 새로운 코드를 추가하더라도 

```js
+
+ doSomething();
```

만 표시되었을 거에요. 그래서 코드의 가장 마지막 라인에 빈 줄을 하나 추가해야합니다.

2020-09-17 15:03 UTC, merged