[Week1][Davidyang2149]Refactor let count remove
CodeSoom/week1-assignment-1 pull request #43
Opened 2020-09-15 13:51 UTC by DavidYang2149

# 1주차 - 과제1
## 요구사항
- [ ] ESLint를 돌린 결과 아무런 문제가 없어야 합니다.
- [ ] 모든 인수 테스트를 통과시켜야 합니다.

## 구현할 기능들
- [x] 강의를 듣고 index.js를 완성합니다.
- [x] let을 사용하지 않고 기존과 동일한 동작이 가능해야 합니다.

## 작업 내용
- let count를 제거 : 불변성을 유지하기 위해 함수 내부에서 처리(캡슐화?)하도록 유도

## 질의
- 의도한 부분에 맞게 작업을 했는지 모르겠습니다. 확인 요청드립니다.
- eslint 검사 시 render() 부분의 'render' was used before it was defined. 경고가 뜨고 있습니다. (작업 진행 중)

2020-09-16 00:42 UTC, hannut91 requested changes
과제의 의도에 맞게 잘 해주셨네요! 이제 render함수는 외부의 환경에 의해 변화하지 않고 내부 파라미터에 의해서만 변하게 되어서 1. 테스트가 쉬워지고 2. 예측 가능성이 좋아졌어요. 

선언되기 이전에 사용됐다는 eslint 에러는 `no-use-before-define`이라는 룰 때문에 그런건데요. 이 룰이 왜 적용하는게 좋다고 하는건지 살펴보시면 좋을 것 같아요. eslint룰을 강하게 해서 코드를 작성하는 연습을 하시면 자연스럽게 좋은 코드를 작성하려는 노력을 하게 되고 코드를 작성하는데 좋은 습관을 들이는데 도움이 될거에요

See also
  - https://eslint.org/docs/rules/no-use-before-define

2020-09-16 00:42 UTC, hannut91 commented on src/index.js
> +  render(addOne);
`addOne`이라는 변수를 하나 만들어서 중간과정을 더 상세하게 설명하신 것 같네요 ㅎㅎ 만약에 `count + 1`이 이미 충분히 설명하고 있다는 생각이 드시면 `inline variable` 리팩터링을 할 수 있을거에요

See also
  - https://refactoring.com/catalog/inlineVariable.html
  - https://github.com/hannut91/refactoring-practice/tree/master/6.4-inline-variable

2020-09-16 02:46 UTC, DavidYang2149 commented on src/index.js
> +  render(addOne);
말씀해주신 내용을 토대로 리팩토링을 적용해 보았습니다. 
코드가 더 간결하게 보이네요. 
감사합니다. 😀

2020-09-16 02:55 UTC, DavidYang2149 commented
말씀하신 내용을 토대로 리팩토링을 진행하였습니다.

1. 변수 인라인 하기.
  - 변수명과 표현식이 같은 의미를 가지기 때문에 리팩토링하여 변수명을 제거.
2. no-use-before-define 문제 해결하기.
  - render 함수 안으로 함수들을 이동.

2020-09-16 15:30 UTC, hannut91 requested changes
리뷰한 것에 대해서 정확하게 반영해주신 것 같아요! 함수의 반환값에 대해서 커멘트 남겼으니 생각해보시면 좋을 것 같아요.

2020-09-17 00:09 UTC, DavidYang2149 commented on src/index.js
> +  const handleClickNumber = (number) => render(number);
네! 해당 내용을 반영하여 리팩토링 해보겠습니다.

2020-09-17 00:39 UTC, DavidYang2149 commented
@hannut91 
함수를 리팩토링하면서 느낀 점에 회고를 남깁니다.

말씀하신 것처럼 하단 `handleClick` 함수 내부에 있는 `render` 함수의 역할은 실행한 결괏값을 리턴하는 게 아닌 것을 상기하며 수정했습니다.
```
const handleClick = (number) => {
  render(number + 1);
}
```

그런데 `handleClick` 함수에 분기 처리를 해주어야 한다면 어떻게 해야 의도를 명확하게 표현할지 궁금해졌습니다.
`1주 차 - 과제 2`에서 제가 작성한 방법은 다음과 같습니다.

```
const handleClick = (number) => {
  if (number === false) {
    return render(0);
  }
  return render(number + 1);
}
```

위 코드는 if문에 해당하는지 여부에 따라 분기 처리를 하게 되고 `render` 함수를 한번 호출하면 거기서 실행이 멈추어야 합니다.
하지만 마치 `render()`의 결괏값을 리턴하는 것처럼 보입니다.

아샬님이 강의를 진행하시며 만들었던 `createElement` 함수에서 답을 찾았습니다.
```
const handleClick = (number) => {
  if (number === false) {
    render(0);
    return; 
  }
  render(number + 1);
}
```

이렇게 변경하니 더 코드가 명확하지는 것 같습니다.

다른 코드도 리팩토링을 진행해봐야겠습니다!

2020-09-17 15:05 UTC, merged

2020-09-20 10:12 UTC, DavidYang2149 commented
## 한 것(Fact)
### 1. `let` 제거하기
#### 왜(why)?
불변성을 유지하기 위해(참조 투명성을 위해).
코드가 불변이면 초기 선언값을 믿고 작업할 수 있다.
### 2. ESLint 사용하기
#### 왜(why)?
코딩 컨벤션에 어긋나는 코드나 안티 패턴을 자동 검출해 준다.
좋은 코딩 스타일과 코드 품질을 만들 수 있다.
나중에 팀으로 작업할 때도 좋은 룰을 만들 수 있다는 생각이 들었다.
### 3. 인수 테스트 통과하기
#### 왜(why)?
인수 테스트를 통해서 기능의 신뢰를 할 수 있다(단, 테스트 케이스가 신뢰할 수 있다는 전제를 가진다).
작성된 테스트 케이스를 통해 코드가 통과되면 심리적인 안정감이 생겼다.

## 느낀 것(Feelings)
### 1. 코드리뷰
2년간 직장생활을 하면서 내가 작성한 코드에 자신감이 없었다.
코드 품질의 기준은 동작이 정상적으로 작동하는지 아닌지의 여부였다.
그동안 코드리뷰가 없어 내 코드의 품질이 어떤지 알지 못해 답답했다. 
이번 코드숨을 통해 내가 어떤 생각으로 코드를 작성했는지 또 어떤 습관을 지니고 있었는지 진단을 받을 수 있었다. 
그리고 내 상태를 알게 되면서 무엇을 고치고 보완해야 하는지 깨달았다. 
### 2. 리팩토링
처음 학원에서 프로그래밍에 대해 배울 때 리팩토링은 *기존 기능을 그대로 유지하면서 내부 구조를 개선*하는 것이라고 배웠다.
처음으로 코드리뷰를 통해 리팩토링해보았다.
사실 리팩토링이라고 불리는 것도 부끄러운 수준이지만 누구든 처음부터 만족하랴.
앞으로 남은 시간동안 열심히 해보자.
### 3. 인수 테스트
개발자 서적에 인수 테스트 혹은 TDD에 대한 개념을 보았는데, 글로 읽을 때는 '아 이런 개념이 있구나' 정도였다.
그런데 이번 인수 테스트를 해보고 코드가 모두 통과하는 것을 보면서 심리적인 안정감과 코드를 신뢰할 수 있게 되었다.
물론 테스트 케이스를 작성하는 방법을 배우고, 또 신뢰할 수 있는 테스트 케이스를 작성하는 것은 별개의 일이다.
앞으로 배울 인수 테스트가 궁금하고 기대된다.

## 배운 것(Findings)
### 1. inline variable 리팩토링 하기
#### 왜(why)?
변수명을 잘 짓는 것도 중요하지만, 우변의 식이 명확한 의미를 가진다면 그대로 대입하는 것이 더 좋은 방법일 수도 있다.
- 참조1 : https://refactoring.com/catalog/inlineVariable.html
- 참조2 : https://github.com/hannut91/refactoring-practice/tree/master/6.4-inline-variable
### 2. 화살표 함수를 사용할 때 중괄호를 잘 고려하기
#### 왜(why)?
화살표 함수를 한줄로 작성할 때는 중괄호를 생략할 수 있다.
하지만 작성한 코드가 반환하는 값이 없을 때는 중괄호를 포함시켜야 한다.
```js
const handleClick = (number) => {
  if (number === false) {
    // 하단의 render(0)은 반환값이 없다.
    render(0);
    return;
  }
  // 여기도 마찬가지로 render(number + 1)의 반환값이 없다.
  render(number + 1);
  return;
}
```
만약 `return render(number + 1);`로 작성했으면 `render(number + 1)`의 결과값을 리턴하는 것처럼 보인다.
그러나 실제 코드의 의도는 `render(number + 1)`의 작업을 진행한 후 종료하는 것이다.