week1-1 remove let
CodeSoom/week1-assignment-1 pull request #45
Opened 2020-09-15 15:02 UTC by JamieShin0201

안녕하세요!

1. count 변수를 render 함수 안으로 이동시켰습니다
2. count 변수의 자료형을 const로 변경하였습니다.
3. handleClick 함수의 매개변수로 count+1을 추가하였습니다.

리뷰 부탁드립니다^_^

2020-09-16 00:46 UTC, hannut91 requested changes
굉장히 잘해주셨네요 ㅎㅎ 동일한 일을 하는 함수가 2개 있어서 중복을 제거하는 일과 변수의 이름만 조금 수정하면 좋을 것 같아요

2020-09-16 00:46 UTC, hannut91 commented on src/index.js
> +function render(cnt) {
숫자가 증가하는 변수라서 count라는 이름을 사용하셨고, cnt로 줄임말을 사용하신 것 같아요. 줄임말은 코드를 읽는 사람에게 있어서 한 번 더 생각하게하고 오해를 불어 일으킬 수 있어서 아주 자명한 상환이 아니면 줄이지 않는게 좋습니다.

2020-09-16 00:46 UTC, hannut91 commented on src/index.js
> +  const count = cnt || 0;
`cnt`값이 없으면 0으로 초기화를 하고 싶으셔서 작성하신 것 같아요. 함수의 매개변수에 기본값을 주고 싶으시다면 아래와 같이 할 수 있습니다.

```js
function render(count = 0) {
  ...
}
```

2020-09-16 00:46 UTC, hannut91 commented on src/index.js
> +}
이 두 함수가 하는 일이 완전히 같은 것 같아요. 하나를 삭제하면 좋을 것 같아요

2020-09-16 04:15 UTC, JamieShin0201 commented
안녕하세요!

1. 같은 동작을 하는 함수를 제거하였습니다.
2. cnt 줄임말 변수 -> count 로 변경하였습니다.
3. render()함수 내에게 const count가 없어도 될거 같아 제거하였습니다.

2020-09-16 15:32 UTC, hannut91 requested changes
과제의 의도에 맞게 잘 해결해주셨네요 ㅎㅎ 이제 render함수는 외부 변수에 의해서 동작이 변하하지 않아서

1. 테스트가 쉬워지고
2. 코드의 예측가능성이 높아져서

더 좋은 코드가 되었네요! 이전이랑 비교했을 때 어떤 변화가 일어났는지 다시 한 번 보시면 좋을 것 같아요

2020-09-16 15:32 UTC, hannut91 commented on src/index.js
> +/* eslint-disable react/react-in-jsx-scope, react/jsx-filename-extension, no-use-before-define */
`no-use-before-define`룰을 disable하지 않고 문제를 해결해보세요. 왜 이룰을 사용하는지 생각해보시면 도움이 되실 것 같습니다. eslint룰을 강력하게 하고 지키려는 연습을 하다보면 더 나은 코드를 작성하려는 노력이 자연스럽게 됩니다.

See also
  - https://eslint.org/docs/rules/no-use-before-define

2020-09-17 10:55 UTC, JamieShin0201 commented on src/index.js
> +/* eslint-disable react/react-in-jsx-scope, react/jsx-filename-extension, no-use-before-define */
함수를 선언하기전에 사용을하면 코드를 볼때 굉장히 혼란스러울거 같습니다.!

render 함수 내에 클릭이벤트를 구현함으로써 해당 문제를 해결하였습니다.!

2020-09-17 15:09 UTC, hannut91 requested changes

2020-09-17 15:09 UTC, hannut91 commented on src/index.js
> +  }
`inputNumber`에서 `input`은 어떤 의미를 드러내나요? 코드를 읽는 사람에게 있어서 어떤 도움을 주고 있나요?

2020-09-18 02:27 UTC, JamieShin0201 commented on src/index.js
> +  }
변수명 짓는게 쉽지 않네요.. ㅠ 
inputNumber 보단 그냥 number로 하는게 더 나을거 같습니다.

처음엔 사용자가 클릭한 값을 받아서 함수에 매개변수로 주는거니 input이라는게 더 명확할거라고 생각했습니다.

2020-09-18 13:48 UTC, hannut91 approved these changes
고생하셨습니다 ㅎㅎ 리뷰에 대한 내용들은 잘 반영해주셨네요. 처음 코드와 마지막 코드까지 어떤 변화가 있었나요?

2020-09-19 13:12 UTC, JamieShin0201 commented
안녕하세요 ㅎ.ㅎ

처음코드와 마지막 코드를 비교했을때 

render 함수 밖에 선언 하였던 let 변수를 사용하지 않고 모든게 render함수 내에서만 처리 되니 render가 아닌 다른함수에 의해 변수값이 변하지 않아 render함수가 모듈화? 된거 같습니다.

2020-09-19 13:23 UTC, hannut91 commented
render함수가 순수함수로 변경되었군요 ㅎㅎ

이 풀리퀘스틀르 닫고 `CodeSoom:JamieShin0201`로 다시 풀리퀘스트를 보내주시면 머지하겠습니다!

2020-09-19 13:58 UTC, closed without merging