Work 1. Remove let statement
CodeSoom/week1-assignment-1 pull request #46
Opened 2020-09-15 15:48 UTC by TaeWoongKim2

let statement를 지우기 위해 Class 개념을 도입했습니다.

Class를 도입한 이유는 다음과 같습니다.

1. let count 는 전역으로 선언되어 있기 때문에 임의의 변경에 취약합니다.

2. 코드가 길어질 경우, 해당 변수에 대한 위치를 찾기 어려워진다고 생각했습니다.

위의 이유로 인해 클래스로 묶어 Getter & Setter 로 관리하면 어떨까 하는 마음에 코드를 작성했습니다.

추가적으로 render()까지 Class 에 묶은 이유는 Count라는 하나의 Component로 생각했습니다.다. render()를 Method Field로 넣음으로써 count 변수의 의미를 뚜렷하게 하기 위함이지만, 해당 방식이 옳은 방식인지는 추가적인 공부 및 멘토님들의 조언 기다립니다.

Git 부터 JSX, 리액트까지 모두 처음 접하는 것으로 따끔한 채찍질 부탁드립니다 : )

2020-09-16 00:52 UTC, hannut91 requested changes
대신 객체를 사용해서 잘해주셨네요 ㅎㅎ 과제의 의도는 immutable하게 값을 관리하는 것과 함수를 순수하게 유지하는 방법을 익히는거에요. 이 방법에 대해 고민해보시고 다시 시도해봐주시면 좋을 것 같습니다.

2020-09-16 00:52 UTC, hannut91 commented on src/index.js
> +        <button type="button" onClick={() => { counter.count += 1; render(); }}>
버튼을 클릭했을 때 값을 증가시키고 다시 렌더를 하도록 하신 것 같아요. 간단한 로직이라면 여기에 inline해도 되지만 지금처럼 두 가지 일을 하고 있을 때는 핸들러 함수로 추출하면 더 읽기 좋은 것 같아요. 

See also
  - https://github.com/hannut91/refactoring-practice/tree/master/6.1-extract-function
  - https://refactoring.com/catalog/extractFunction.html

2020-09-16 00:52 UTC, hannut91 commented on src/index.js
> +};
let 대신에 const를 사용하여 `counter`변수는 재할당할 수 없게 해주셨네요 ㅎㅎ 하지만 객체의 속성은 여전히 재할당이 가능합니다. 그래서 어디서 이 값이 변하는지 추적하기 어렵고, 이를 사용하는 render 함수는 외부의 환경에 의해 동작이 달라지므로 테스트하기 어렵고 어떻게 동작할지 예측하기가 어려워요. `render`함수가 매개변수에 의해서만 동작이 달라진다면 어떨까요?

2020-09-16 08:09 UTC, TaeWoongKim2 commented on src/index.js
> +        <button type="button" onClick={() => { counter.count += 1; render(); }}>
> 대신 객체를 사용해서 잘해주셨네요 ㅎㅎ 과제의 의도는 immutable하게 값을 관리하는 것과 함수를 순수하게 유지하는 방법을 익히는거에요. 이 방법에 대해 고민해보시고 다시 시도해봐주시면 좋을 것 같습니다.

과제의 의도에 따라 다시 수정하겠습니다 : )
오늘은 회사 작업일로 철야입니다..ㅠㅠ
내일 저녁에 다시 열심히 달리겠습니다!!

2020-09-16 08:11 UTC, TaeWoongKim2 commented on src/index.js
> +};
`render` 함수에 매개변수를 넣는 방법을 생각을 못했네요.
매개변수에 초기값을 넣어준다면, 외부에서 선언할 필요도 없겠군요.
좋은 조언 감사합니다!!! 👍 👍 👍

2020-09-16 15:38 UTC, hannut91 commented
도움이 필요하시다면 언제든 문의 주세요 ㅎㅎ

2020-09-17 14:02 UTC, TaeWoongKim2 commented
철야 끝에 돌아왔습니다. 코드리뷰 해주신대로 `render()`함수의 매개변수를 활용하여 코드를 변경해봤습니다.
참조해주신 링크도 좋은 방향으로 깔끔한 코드를 짤 수 있는 방향을 잡아줘서 좋네요 😁
검토 한 번 더 요청드립니다.

2020-09-17 15:13 UTC, hannut91 approved these changes
리뷰를 잘 반영해주신 것 같아요 ㅎㅎ 처음 코드랑 비교했을 때 어떤 변화가 있나요?

2020-09-17 15:13 UTC, hannut91 commented on src/index.js
> +/* eslint-disable no-underscore-dangle */
이 룰은 어떤것 때문에 disable 하신건가요?

2020-09-17 15:14 UTC, merged

2020-09-17 15:57 UTC, TaeWoongKim2 commented on src/index.js
> +/* eslint-disable no-underscore-dangle */
아하, 해당 룰은 과제1 처음 코드리뷰 시, Class로 변경하여 리뷰를 받은 바 있습니다.
Class 에서 underscore field를 만들면서 eslint가 전부 붉은색 줄을 내뿜더라구요 ㅠㅠ...
아마 그때 위 룰을 추가하여 disable 시켜준 것 같습니다 : )

2020-09-17 16:02 UTC, TaeWoongKim2 commented
먼저 영석님의 빠른 리뷰 감사드립니다. 코드리뷰라는 것을 처음 받아보니 행복하네요 👍 
처음 코드와 비교했을 때, 불필요한 Function과 Field 들이 제거되어 코드가 확실히 간결해 졌습니다. 
그리고 `render()`의 파라미터로 변경하니 `count`라는 변수를 외부에서 찾을 필요도 없어진 듯 합니다.
외부에서 let으로 선언한 경우보다 한 곳에서 관리가 되는 듯 한 느낌입니다. 
이를 의도하신 과제가 맞을까요? ㅎㅎ..