Week1-assigment-1
CodeSoom/week1-assignment-1 pull request #47
Opened 2020-09-16 04:35 UTC by comejtome508

현재 const로 바꾼 뒤 parameter로 값을 전달하여 문제를 풀어가는 중입니다.
count의 경우 처음에는 render() 안에 선언을 해주었는데 블록스코프 때문에 0으로 초기화되는 듯 해서 
전역변수로 위치를 변경하였는데 여전히 count의 값이 0으로 되어서 고민하는 방향이 맞는지 확인 한번 해주시면 감사하겠습니다.

2020-09-16 12:04 UTC, Kihyun92 commented
변수의 선언 위치와 스코프에 대해 많이 고민해보고 느껴보고 계시는것 같네요! 그리고 파라미터로 값을 전달하여 문제를 해결하는 방향도 좋습니다.😄
count를 render function 내부에서 선언하였다면, 당연히 render 함수가 호출 될때마다 초기화 됐을 겁니다.ㅎㅎ

이번 과제의 의도를 조금 고민해보시면 좋을것 같습니다. let을 사용하지 말라, 그럼 const를 사용하라는 의미일까요?
역으로 질문하게 됐네요 ㅎㅎ 조금 더 고민 해보시면 답을 찾으실 것 같습니다! 👍

2020-09-16 13:06 UTC, comejtome508 commented
답변 감사합니다!! 초기 값을 설정해주는데 있어서 const 밖에 없다는 생각에 갇혀서 풀리지 않았습니다. 
재할당과 불변성을 유지하면서 초기값에 변화를 주려고 해서 문제가 있었는데 초기 값 역시 파라미터로 전달하는 것으로 방향을 잡고 lint 외의 문제는 해결을 하였습니다! 감사합니다^^

2020-09-19 08:22 UTC, Kihyun92 requested changes

2020-09-19 08:22 UTC, Kihyun92 commented on src/index.js
> +function render(resultValue) {
제가 너무 늦게 피드백을 남긴것 같네요~
resultValue 이외에 여러 상태값들을 전달해야 할 경우엔 어떻게 해야할까요? 확장성에 대해서도 고민해보시면 좋을 것 같아요~

2020-09-20 06:30 UTC, Kihyun92 approved these changes
고생하셨습니다~ 👍
이번 과제를 통해 무엇을 배우셨나요?
과제는 approve 하겠습니다~ :)

2020-10-05 12:48 UTC, merged