feat) week1-assignment-1 과제 제출
CodeSoom/week1-assignment-1 pull request #48
Opened 2020-09-16 08:27 UTC by wjy5446

## task

- 수업 수강후 베이스 코드 작성
- let를 사용하지 않은 코드로 수정
- eslint에 no-use-before-define 룰 disable 설정

2020-09-16 10:53 UTC, Kihyun92 commented on src/index.js
> +/* eslint-disable react/react-in-jsx-scope, react/jsx-filename-extension, no-use-before-define */
```suggestion
/* eslint-disable react/react-in-jsx-scope, react/jsx-filename-extension */
```
`no-use-before-define`을 disable 하지 않고 코드를 작성하려면 어떻게 해야할까요? 한번 고민해보시면 좋을것 같습니다~

2020-09-16 10:58 UTC, wjy5446 commented on src/index.js
> +/* eslint-disable react/react-in-jsx-scope, react/jsx-filename-extension, no-use-before-define */
no-use-before-define 룰을 disable 하지 않는 부분이 존재하군요. :)
이 부분 해결해보려고 고민해 보았는데, 어떻게 해야 할지 도저히 떠오르지 않아서 그냥 disable 했는데 ㅎㅎ

한번 disable 하지 않는 방향으로 적용해 보겠습니다.

2020-09-16 11:12 UTC, Kihyun92 requested changes
이번 과제의 의도를 고민하시고 잘 파악해주신것 같아요! 시작이 좋습니다 👍

2020-09-16 11:12 UTC, Kihyun92 commented on src/index.js
> +}
DOM 객체에 직접 접근하여 count 값을 가져오도록 하셨네요~
이 경우에 DOM 객체에 직접 접근하여 값을 가져오는게 복잡하지만 쉬운 방법일 수도 있습니다. 하지만 더 다양한 값을 컨트롤해야하는 경우에는 어떨까요? DOM객체에 접근해서 값을 가져오고 다시 DOM에 반영하고.. 조금 복잡해지고 관리가 어려워질것 같네요.
명확한 상태값을 가지고 있고, 그 상태값을 화면에 보여주도록 처리해보면 어떨까요?

2020-09-16 11:27 UTC, wjy5446 commented on src/index.js
> +}
빠른 피드백 감사드립니다. 

말씀해주신 대로 DOM 접근해서 값을 가져오면 다양한 값을 조작할 때에는 매우 복잡해질 수 있을 것 같네요 ㅎㅎ

그럼 명확한 상태값을 가지고 있다는 말이 render 함수 내에서 상태값을 관리해야 된다는 말씀이신가요??

2020-09-16 11:42 UTC, wjy5446 commented
말씀하신대로 상태값으로 화면을 출력하는 방식으로 변경했습니다. 
변경해보니 코드가 많이 단순해지는 효과가 있네요!! 
수정해보니 이벤트 함수도 단순해져서 하나의 함수로도 표현이 가능해지네요!!

2020-09-16 12:24 UTC, Kihyun92 requested changes

2020-09-16 12:24 UTC, Kihyun92 commented on jsconfig.json
> +}
```suggestion
}

```
PR을 올리시고, 제출한 PR을 한번 쭉 확인해보시면서 이런 warning을 수정해주시면 더 완벽해질 것 같습니다~

2020-09-16 12:24 UTC, Kihyun92 commented on src/index.js
> +  }
함수의 파라미터를 i라는 아무 의미없는 이름으로 짓기 보다는, 어떤 값을 전달받을지 유추할 수 있는 네이밍이면 더 좋을 것 같습니다~

그리고 현재 handleClick 함수는 단순히 i값을 전달받아서 바로 render함수에 넘겨주는 방식으로 되어있네요ㅎㅎ
이런 단순한 역할을 할 경우 button의 onClick에서 바로 호출하는건 어떨까요?

2020-09-16 12:28 UTC, Kihyun92 commented on src/index.js
> +}
스스로 답을 찾으신 것 같네요~ 👍

함수의 인자를 통해서 명확히 상태값을 나타내고, 불변성을 가질 수 있다는 의미로 말씀 드린건데 제가 어렵게 말씀 드린것 같네요 😅

2020-09-16 12:52 UTC, wjy5446 commented on src/index.js
> +}
어려워도 피드백 때문에 좀 더 좋은 코드를 작성할 수 있었습니다 ㅎㅎ

2020-09-16 12:53 UTC, wjy5446 commented on jsconfig.json
> +}
혹시 제가 pr이 익숙하지 않아서 그런데 해당 warning은 어디에서 확인할 수 있을 까요??

2020-09-16 12:56 UTC, wjy5446 commented on jsconfig.json
> +}
아니면 따로 warning 메세지가 출력되는 게 아니라 육안으로 확인하는 건가요??

2020-09-16 13:00 UTC, wjy5446 commented on src/index.js
> +  }
간단한 함수는 바로 호출하는 것이 더 효율적일 수 있겠네요 ㅎㅎ
감사합니다.

2020-09-16 13:05 UTC, Kihyun92 commented on jsconfig.json
> +}
![image](https://user-images.githubusercontent.com/35797540/93341005-8df2ac80-f868-11ea-8cf4-3522515b4a56.png)
Pull requests -> Files changed에서 확인 가능합니다~ 한번 확인해보시겠어요?

2020-09-16 13:19 UTC, wjy5446 commented
말씀 해주신대로 button의 onClick 함수에서 코드를 실행하는 방식으로 변경해 보았습니다.
해당 방식으로 변경하기 코드가 간결해지는 효과를 볼 수 있었습니다. 

하지만 여기서 궁금한 것이 지금과 같이 코드 량이 적을 경우에는 익명함수를 통해서 직접 호출하는 방식이 효율적이지만, 
코드 량이 많을 경우에는 간단한 로직이라도 함수 정의를 해주고, 호출하는 것이 가독성이 좋을 것 같다 라는 생각이 들었습니다.

이에 대해서 어떻게 생각하시는 지 궁금합니다. :)

2020-09-16 13:53 UTC, wjy5446 commented on jsconfig.json
> +}
github에 이런 기능이 있는지도 몰랐네요. 감사합니다. ㅎㅎ
제가 그거 보고 제안해주신 코드로 commit했는 데 이렇게 하는 게 맞는 지 모르겠네요 ㅎㅎ

2020-09-16 14:03 UTC, Kihyun92 commented
> 말씀 해주신대로 button의 onClick 함수에서 코드를 실행하는 방식으로 변경해 보았습니다.
> 해당 방식으로 변경하기 코드가 간결해지는 효과를 볼 수 있었습니다.
> 
> 하지만 여기서 궁금한 것이 지금과 같이 코드 량이 적을 경우에는 익명함수를 통해서 직접 호출하는 방식이 효율적이지만,
> 코드 량이 많을 경우에는 간단한 로직이라도 함수 정의를 해주고, 호출하는 것이 가독성이 좋을 것 같다 라는 생각이 들었습니다.
> 
> 이에 대해서 어떻게 생각하시는 지 궁금합니다. :)


`코드 량이 많을 경우에는 간단한 로직이라도 함수 정의를 해주고, 호출하는 것이 가독성이 좋을 것 같다` 저도 이 말에 매우 동의합니다~ 말씀하신 부분은 협업을 할때 매우 중요한 부분이죠. 간단한 로직을 가진 함수라도, 해당 함수를 따로 정의해 사용한다면 재사용성과 가독성 부분에서 도움이 된다고 생각합니다.😁

제가 앞에서 직접 호출하는게 어떨지 의견 드렸던 부분은 코드량이 적어서가 아니라,
1. 해당 함수가 단순히 i값을 전달받아서 바로 다른 함수를 호출하는 방식이었고,
2. 호출되는 함수 또한 render라는 이름에서 기능을 유추가능하기 때문에 직접 호출하는게 어떨지 의견을 드렸던것 같습니다 😊

제 의견을 그냥 받아들이지 않고, 이렇게 한번 더 생각하시고 피드백 주셔서 너무 감사하네요 :)

2020-09-16 14:09 UTC, Kihyun92 commented on src/index.js
> +/* eslint-disable react/react-in-jsx-scope, react/jsx-filename-extension, no-use-before-define */
https://eslint.org/docs/rules/no-use-before-define 이 문서를 참고하시면 왜 이런 룰이 생겼는지 도움이 되실 것 같습니다 💯

2020-09-16 14:14 UTC, wjy5446 commented
제가 협업으로 코드를 작성해 본 적이 별로 없어서 궁금해서 물어보았는데 친절하게 답변해주셔서 감사합니다. :)
저에게 큰 도움이 되었습니다. ㅎㅎ

2020-09-20 06:31 UTC, Kihyun92 approved these changes
고생하셨습니다~ 👍
혹시 다음에 더 시도해보고 싶은게 있을까요? 한번 고민해보시면 좋겠습니다 ㅎㅎ
과제는 approve 하겠습니다~ :)

2020-09-20 09:05 UTC, wjy5446 commented
리뷰 감사드립니다. 👍 

해당 과제에서 더 시도해보고 싶은 부분은 지금은 없는 것 같습니다. ㅎㅎ
다음 과제에서도 수정할 부분 있으면, 더 적극적으로 피드백 해주시면 감사드리겠습니다. 
적극 반영해서 코드 수정해겠습니다. 

주말에도 리뷰하시느라 고생하셨습니다. :)

2020-10-05 12:50 UTC, merged