Hyejineee
CodeSoom/week1-assignment-1 pull request #50
Opened 2020-09-17 15:07 UTC by hyejineee

2020-09-17 15:43 UTC, Kihyun92 requested changes
render 함수가 외부 변수에 의해 동작이 변화하지 않도록 하는 과제의 의도에 맞게 잘 해결해주신것 같네요~

과제를 할때 시간이 걸린다면 말씀해주시고 같이 고민해봐도 좋을것 같습니다~

2020-09-17 15:43 UTC, Kihyun92 commented on src/index.js
> +        </button>
이번 과제1의 요구사항 중에 하나가 `강의를 듣고 index.js를 완성합니다.` 였습니다~ 

1강 -> JSX 챕터에 있는 강의를 마지막까지 듣고, 코드를 따라해보는것도 과제중 일부 였는데요. 이 부분은 강의를 한번 더 확인해보시고 빠진 코드들 추가해주세요~

어렵지 않은 코드니까 얼마 안걸리실 겁니다!

2020-09-17 15:50 UTC, hyejineee commented on src/index.js
> +        </button>
아하! map()을 사용하는 부분을 활용하는 테스트였군요! 알겠습니다!!

2020-09-20 06:32 UTC, Kihyun92 approved these changes
고생하셨습니다~ 👍
다음에 더 배우고 싶은게 있을까요? 한번 고민해보셔도 좋겠네요~
과제는 approve 하겠습니다~ :)

2020-10-05 12:49 UTC, merged