[week1] remove let
CodeSoom/week1-assignment-1 pull request #51
Opened 2020-09-18 05:26 UTC by shinseungyup

let을 사용하지 않고 코드 작성

2020-09-18 15:10 UTC, Kihyun92 requested changes
객체를 활용해 문제를 해결하는 시도 좋습니다! 
하지만 문제 해결에 집중하는것도 중요하지만, 조금 더 이번 과제의 의도에 대해서 생각해보셨으면 좋겠습니다~ 

let을 사용하지 말라는 이유가 무엇일까요? const를 쓰라는 말 일까요?
좀 더 고민해보시면 금방 답을 찾으실 것 같습니다~👍

2020-09-18 15:10 UTC, Kihyun92 commented on src/index.js
> +};
count 값을 state를 통해 관리하도록 처리하셨네요~ 이 방법이 잘못된건 아닙니다.
하지만, 이번 과제의 의도를 한번 더 생각해보시면 좋을 것 같습니다.

let을 쓰지 않고 값을 컨트롤 하기위해 const로 객체를 선언한다고 해도 객체 내부 속성 값이 안바뀌는건 아니죠. 그렇다면 이 속성은 언제 변할지 예측하기 어려워지겠죠? ☺️

2020-09-18 23:48 UTC, shinseungyup commented on src/index.js
> +};
과제의 의도가 무엇인지 먼저 생각안하고 한거 같네요.  의도를 생각해보고 다시 수정하겠습니다.

2020-09-19 04:17 UTC, Kihyun92 requested changes

2020-09-19 04:17 UTC, Kihyun92 commented on src/index.js
> +  }
두 함수가 동일한 동작을 수행하고 있네요~ 그리고 이 경우엔 단순히 value를 받아서 render에 넘겨주는 역할만 하고 있네요. 조금 더 개선 할 수 있을 것 같습니다!

2020-09-19 08:17 UTC, Kihyun92 requested changes

2020-09-19 08:17 UTC, Kihyun92 commented on src/index.js
> +function render(count = 0) {
count 이외에 다른 상태값이 추가될 경우엔 어떻게 해야할까요?
확장성에 대해서 고민해보셔도 좋을 것 같습니다~

2020-09-19 11:28 UTC, shinseungyup commented on src/index.js
> +  }
두 함수를 삭제하고 이벤트 onClick 코드에서 직접 render를 호출하도록 수정하였습니다.

2020-09-20 06:33 UTC, Kihyun92 approved these changes
고생하셨습니다~ 👍
이번 과제를 하면서 좋았던점과 아쉬웠던 점이 있을까요?
과제는 approve 하겠습니다~ :)

2020-10-05 12:48 UTC, merged