1주차과제
CodeSoom/week1-assignment-1 pull request #52
Opened 2020-09-19 13:15 UTC by hanamDeveloper

2020-09-19 14:19 UTC, Kihyun92 requested changes
이번 과제의 의도에 대해서 조금 더 생각해보시고 하나하나 수정하신다면 금방 approve 될것 같습니다! 👍

2020-09-19 14:19 UTC, Kihyun92 commented on src/index.js
> +const count = [0];
let을 피하기 위해서 const를 사용하셨네요~ const 로 바꿨더니 할당이 안되니 배열로 count 값을 할당하셨구요.

이 방법보다는 뭔가 immutable하게 상태값을 관리할 수 있는 방법이 있을 것 같습니다! 조금 더 고민해보시면 좋을 것 같아요~

2020-09-19 14:29 UTC, Kihyun92 commented
그리고 가능하시면, Pull request시에 작업 내용 등을 요약해서 적어주시면 좋습니다!
commit 메시지 또한 어떤 작업에 대한 커밋인지를 적어주면 좋아요~
사용하시다보면 금방 익숙해지실겁니다 😊

https://github.com/CodeSoom/git-training 도 많이 참고해주세요~

2020-09-20 08:52 UTC, Kihyun92 requested changes

2020-09-20 08:52 UTC, Kihyun92 commented on src/index.js
> +function render(count = 0) { // count를 render의 매개변수로 넣어준다.
주석은 필요 없을 것 같습니다~ 커밋을 하기 전엔 항상 주석은 제거해주세요. 
그리고 주석을 달기보다는 주석 없이도 이해 되는 코드를 작성하기 위해 고민하시는게 좋습니다! 👍

2020-09-20 09:25 UTC, hanamDeveloper commented on src/index.js
> +function render(count = 0) { // count를 render의 매개변수로 넣어준다.
넵! 감사합니다!

2020-09-20 16:15 UTC, Kihyun92 approved these changes

2020-09-20 16:16 UTC, Kihyun92 commented
이번과제를 통해 무엇을 할 수 있게 되셨나요? 한번 생각해보시면 좋겠습니다~
이번 과제는 approve 하겠습니다~

2020-10-05 12:47 UTC, merged